-- =====================================================================
-- Migration: Create user_favorites table
-- Purpose: Store user-specific favorites for quick access to entities
-- Pattern: User-owned data with RLS (like notifications table)
-- =====================================================================

-- Create table
CREATE TABLE user_favorites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMPTZ DEFAULT NULL
);

-- Comments
COMMENT ON TABLE user_favorites IS 'User-specific favorites for quick access to contacts, organizations, etc.';
COMMENT ON COLUMN user_favorites.user_id IS 'Reference to authenticated user';
COMMENT ON COLUMN user_favorites.entity_type IS 'Resource type: contacts, organizations';
COMMENT ON COLUMN user_favorites.entity_id IS 'ID of the favorited entity';
COMMENT ON COLUMN user_favorites.display_name IS 'Cached display name for sidebar rendering';
COMMENT ON COLUMN user_favorites.deleted_at IS 'Soft delete timestamp. NULL = active record.';

-- Unique constraint: One favorite per (user_id, entity_type, entity_id) for active records
CREATE UNIQUE INDEX idx_user_favorites_unique_active
  ON user_favorites (user_id, entity_type, entity_id)
  WHERE deleted_at IS NULL;

-- Performance indexes
CREATE INDEX idx_user_favorites_user_id ON user_favorites (user_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_user_favorites_deleted_at ON user_favorites (deleted_at) WHERE deleted_at IS NULL;

-- Enable RLS
ALTER TABLE user_favorites ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Users can only see their own favorites (active only)
CREATE POLICY "select_own" ON user_favorites
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid() AND deleted_at IS NULL);

-- RLS Policy: Users can create their own favorites
CREATE POLICY "insert_own" ON user_favorites
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

-- RLS Policy: Users can update their own favorites (for soft delete)
CREATE POLICY "update_own" ON user_favorites
  FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- RLS Policy: Users can delete their own favorites
CREATE POLICY "delete_own" ON user_favorites
  FOR DELETE
  TO authenticated
  USING (user_id = auth.uid());
