// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
// import storybook from "eslint-plugin-storybook";

// NOTE: eslint-plugin-tailwindcss does not support Tailwind CSS v4 yet
// The plugin is installed for future use when v4 support is added
// REPLACED WITH: Custom local rule that enforces semantic colors (see below)
// import tailwindcss from "eslint-plugin-tailwindcss";

import jsxA11y from "eslint-plugin-jsx-a11y";

// Local ESLint rule for semantic color enforcement (P0 - addresses 243 fix commits)
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const noLegacyTailwindColors = require("./eslint-local-rules/no-legacy-tailwind-colors.cjs");

import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Color System ESLint Configuration
 *
 * This configuration enforces the new OKLCH-based color system and prevents
 * the use of legacy Tailwind color classes that don't align with our design system.
 *
 * BANNED PATTERNS:
 * - Legacy color utilities: text-green-600, bg-gray-200, border-blue-300, etc.
 * - Direct color values that bypass the semantic color system
 *
 * ALLOWED PATTERNS:
 * - Semantic color tokens: primary, secondary, destructive, muted, accent
 * - Tag color classes: tag-warm, tag-green, tag-blue, etc.
 * - Theme-aware utilities that use CSS variables
 *
 * Note: eslint-plugin-tailwindcss has limited Tailwind v4 support, so some
 * rules are set to "warn" instead of "error" to prevent false positives.
 */

// Legacy color patterns that should be replaced with semantic tokens
// These are documented for reference but enforcement is handled by eslint-plugin-tailwindcss
const bannedColorPatterns = [
  // Ban legacy text colors
  /text-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy background colors
  /bg-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy border colors
  /border-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy ring colors
  /ring-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy divide colors
  /divide-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy placeholder colors
  /placeholder-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy outline colors
  /outline-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy decoration colors
  /decoration-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy accent colors
  /accent-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy caret colors
  /caret-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy fill colors
  /fill-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
  // Ban legacy stroke colors
  /stroke-(gray|green|blue|red|yellow|purple|pink|indigo|cyan|orange|lime|emerald|teal|sky|violet|fuchsia|rose|amber)-\d{2,3}/,
];

export default tseslint.config(
  {
    ignores: [
      "dist",
      "node_modules",
      "build",
      "lib",
      "esm",
      "prism.js",
      "packages/create-react-admin/templates/**",
      ".github",
      "archive/**", // Legacy/deprecated code - not actively maintained
      "src/types/database.generated.ts", // Auto-generated by Supabase CLI
      "src/types/database.types.ts", // Auto-generated by Supabase CLI
    ],
  },
  // TypeScript configuration
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      // "tailwindcss": tailwindcss, // Disabled - replaced with local-rules
      "jsx-a11y": jsxA11y,
      // Local rules for semantic color enforcement (P0 - 243 fix commits addressed)
      "local-rules": {
        rules: {
          "no-legacy-tailwind-colors": noLegacyTailwindColors,
        },
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          varsIgnorePattern: "^_",
          argsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/consistent-type-imports": "warn",
      // Constitution: TypeScript conventions - interface for objects, type for unions
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],

      // Tailwind CSS rules for color system enforcement
      // Custom local rule enforces semantic colors (P0 - addresses 243 fix commits)
      "local-rules/no-legacy-tailwind-colors": "error",

      // Future rules when official eslint-plugin-tailwindcss supports Tailwind v4:
      // "tailwindcss/no-custom-classname": [
      //   "error",
      //   {
      //     "whitelist": [
      //       "tag-warm", "tag-green", "tag-blue", "tag-purple",
      //       "tag-amber", "tag-red", "tag-teal", "tag-indigo",
      //       "animate-.*", "tw-.*", "container", "prose",
      //       "group-.*", "peer-.*", "data-\\[.*\\]:.*", "aria-\\[.*\\]:.*"
      //     ]
      //   }
      // ],
      // "tailwindcss/classnames-order": "warn",
      // "tailwindcss/enforces-negative-arbitrary-values": "warn",
      // "tailwindcss/enforces-shorthand": "warn",
      // "tailwindcss/no-contradicting-classname": "error",

      // JSX A11y rules for color contrast validation
      "jsx-a11y/no-onchange": "off", // React handles onChange properly

      // Prevent form-level validation (Constitution Principle #3: Single-point validation at API boundary only)
      "no-restricted-syntax": [
        "error",
        {
          selector: "JSXAttribute[name.name='validate']",
          message:
            "[VALIDATION] Form-level validation is forbidden per Engineering Constitution. All validation must occur at the API boundary (data provider) using Zod schemas. Use helper text and asterisks for visual cues instead.",
        },
      ],

      // Prevent validation-related imports (Constitution Principle #3)
      // and direct Supabase access (Constitution Principle #2: Single Source of Truth)
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "ra-core",
              importNames: [
                "required",
                "email",
                "minLength",
                "maxLength",
                "minValue",
                "maxValue",
                "number",
                "regex",
                "choices",
              ],
              message:
                "[VALIDATION] React Admin validators are forbidden. Use Zod schemas at the API boundary instead.",
            },
            {
              name: "../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
            {
              name: "../../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
            {
              name: "../../../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
          ],
        },
      ],

      // Prevent reintroduction of legacy fields (Constitution Principle #16)
      "no-restricted-properties": [
        "error",
        {
          object: "Contact",
          property: "company_id",
          message:
            "[DEPRECATED] Contact.company_id is removed. Use contact_organizations junction table instead.",
        },
        {
          object: "Contact",
          property: "is_primary_contact",
          message:
            "[DEPRECATED] Contact.is_primary_contact is removed. Use is_primary field in contact_organizations junction table.",
        },
        {
          object: "Opportunity",
          property: "company_id",
          message:
            "[DEPRECATED] Opportunity.company_id is removed. Use customer_organization_id instead.",
        },
        {
          object: "Opportunity",
          property: "archived_at",
          message:
            "[DEPRECATED] Opportunity.archived_at is removed. Use deleted_at for soft deletes instead.",
        },
      ],

      // Console statement restrictions (CQ-002 audit finding)
      // Allow console.warn and console.error for actual warnings/errors
      // Warn on console.log to encourage use of devLog from @/lib/devLogger
      "no-console": [
        "warn",
        {
          allow: ["warn", "error"],
        },
      ],
    },
    // Settings for future Tailwind v4 support
    // settings: {
    //   tailwindcss: {
    //     callees: ["classnames", "clsx", "cn", "cva"],
    //     config: "tailwind.config.js",
    //     cssFiles: ["!**/node_modules/**", "!**/dist/**", "!**/build/**", "**/*.css"],
    //     cssFilesRefreshRate: 5_000,
    //     removeDuplicates: true,
    //     skipClassAttribute: false,
    //     whitelist: [],
    //     tags: [],
    //     classRegex: "^(class(Name)?|tw)$",
    //   },
    // },
  },
  // Logger infrastructure - console is the output mechanism
  {
    files: ["src/lib/logger.ts", "src/lib/devLogger.ts"],
    rules: {
      "no-console": "off",
    },
  },
  // Test file configuration - enforces test isolation patterns (P0 - addresses 189 testing commits)
  {
    files: ["**/*.test.{ts,tsx}", "**/__tests__/**/*.{ts,tsx}", "**/tests/**/*.{ts,tsx}"],
    rules: {
      "no-console": "off",
      "no-restricted-syntax": [
        "error",
        // Inherit the form validation rule from main config
        {
          selector: "JSXAttribute[name.name='validate']",
          message:
            "[VALIDATION] Form-level validation is forbidden per Engineering Constitution. All validation must occur at the API boundary (data provider) using Zod schemas. Use helper text and asterisks for visual cues instead.",
        },
        // Test context rule: require renderWithAdminContext wrapper
        {
          selector: "CallExpression[callee.name='render'][arguments.0.type='JSXElement']",
          message:
            "[TEST CONTEXT] Use renderWithAdminContext() from 'src/tests/utils/render-admin.tsx' instead of bare render(). This ensures proper React Admin context.",
        },
      ],
    },
  },
  // Notification architecture: Block direct sonner imports (use useNotify/useSafeNotify)
  // Sonner is an internal renderer only — accessed through notification.tsx
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/components/ra-wrappers/notification.tsx", // Runtime renderer
      "src/components/ui/sonner.tsx", // Storybook-only wrapper
      "src/components/ui/sonner.stories.tsx", // Storybook stories
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "sonner",
              message:
                "[NOTIFICATION] Direct sonner imports are forbidden. Use useNotify() or useSafeNotify() instead. Sonner is an internal renderer in notification.tsx only.",
            },
          ],
        },
      ],
    },
  },
  // Feature code restrictions: Enforce Tier 2 wrapper usage (UI_STANDARDS.md)
  // Blocks direct react-admin input imports in atomic-crm features
  {
    files: ["src/atomic-crm/**/*.{ts,tsx}"],
    ignores: ["src/atomic-crm/**/__tests__/**", "src/atomic-crm/**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            // Inherit existing restrictions from main config
            {
              name: "ra-core",
              importNames: [
                "required",
                "email",
                "minLength",
                "maxLength",
                "minValue",
                "maxValue",
                "number",
                "regex",
                "choices",
              ],
              message:
                "[VALIDATION] React Admin validators are forbidden. Use Zod schemas at the API boundary instead.",
            },
            {
              name: "../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
            {
              name: "../../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
            {
              name: "../../../providers/supabase/supabase",
              message:
                "[SINGLE SOURCE OF TRUTH] Direct Supabase imports are forbidden. All database operations must go through unifiedDataProvider.",
            },
            // Feature code restriction: Use wrapped inputs from Tier 2 (UI_STANDARDS.md)
            // Only blocks visual INPUT components, not data containers (ReferenceInput, ArrayInput, etc.)
            {
              name: "react-admin",
              importNames: [
                "TextInput",
                "SelectInput",
                "AutocompleteInput",
                "NumberInput",
                "BooleanInput",
                "DateInput",
                "AutocompleteArrayInput",
                "RadioButtonGroupInput",
                "FileInput",
                "ImageInput",
              ],
              message:
                "[THREE-TIER ARCHITECTURE] Use wrapped inputs from @/components/ra-wrappers/ instead of direct react-admin imports. See UI_STANDARDS.md for Tier 2 component requirements.",
            },
          ],
        },
      ],
    },
  },
  // JavaScript/MJS configuration (for scripts)
  {
    extends: [js.configs.recommended],
    files: ["**/*.{js,mjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      "no-unused-vars": [
        "error",
        {
          varsIgnorePattern: "^_",
          argsIgnorePattern: "^_",
        },
      ],
    },
  }
  // Storybook config disabled due to missing dependency
  // storybook.configs["flat/recommended"],
);
