-- ==========================================================================
-- Crispy CRM — Reference / Config Tables (Reference Snapshot)
-- Last synced: 2026-03-04 | Migrations: 20260214003329..20260303120000
-- WARNING: Read-only reference. Do NOT execute directly. Use migrations.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- 1. segments — Organization classification segments (hierarchical)
-- --------------------------------------------------------------------------
CREATE TABLE public.segments (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  segment_type text NOT NULL DEFAULT 'industry',
  parent_id    bigint REFERENCES public.segments(id),
  created_by   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  deleted_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
-- Unique: segments_name_type_case_insensitive_idx on lower(name), segment_type
-- FK note: created_by ON DELETE SET NULL (migration 20260303100000)
-- RLS: select_segments, segments_insert_privileged, segments_update_privileged, segments_delete_admin

-- --------------------------------------------------------------------------
-- 2. tags — Tags for contacts/organizations
-- --------------------------------------------------------------------------
CREATE TABLE public.tags (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  color       text,
  deleted_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
-- RLS: authenticated_select_tags, tags_insert_privileged, tags_soft_delete_authenticated,
--      tags_delete_privileged, tags_service_role
-- Triggers: trg_cleanup_tag_references, update_tags_updated_at

-- --------------------------------------------------------------------------
-- 3. dashboard_snapshots — Pre-computed dashboard metrics per sales rep
-- --------------------------------------------------------------------------
CREATE TABLE public.dashboard_snapshots (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_id      bigint NOT NULL REFERENCES public.sales(id) ON DELETE RESTRICT,
  snapshot_date date NOT NULL DEFAULT CURRENT_DATE,
  metrics       jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (sales_id, snapshot_date)
);
-- RLS: authenticated_select_dashboard_snapshots (own or manager/admin)

-- --------------------------------------------------------------------------
-- 4. notifications — User notifications
-- --------------------------------------------------------------------------
CREATE TABLE public.notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type       text NOT NULL,
  title      text,
  message    text,
  data       jsonb,
  read       boolean DEFAULT false,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
-- RLS: authenticated_select_own_notifications, authenticated_update_own_notifications,
--      service_insert_notifications, service_delete_old_notifications
-- Triggers: trigger_cleanup_old_notifications

-- --------------------------------------------------------------------------
-- 5. audit_trail — Audit log (append-only, trigger-written)
-- --------------------------------------------------------------------------
CREATE TABLE public.audit_trail (
  audit_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name  text NOT NULL,
  record_id   bigint,
  operation   text NOT NULL,
  changed_by  bigint REFERENCES public.sales(id),
  changed_at  timestamptz NOT NULL DEFAULT now(),
  old_data    jsonb,
  new_data    jsonb,
  field_name  text,
  old_value   text,
  new_value   text
);
-- RLS: audit_trail_admin_manager_only (SELECT only; rows inserted by triggers only)
