-- ==========================================================================
-- Crispy CRM — Notes Tables (Reference Snapshot)
-- Last synced: 2026-03-04 | Migrations: 20260214003329..20260303120000
-- WARNING: Read-only reference. Do NOT execute directly. Use migrations.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- 1. contact_notes
-- --------------------------------------------------------------------------
CREATE TABLE public.contact_notes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id  bigint NOT NULL REFERENCES public.contacts(id) ON DELETE RESTRICT,
  sales_id    bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  created_by  bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  updated_by  bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  date        timestamptz DEFAULT now(),
  note        text,
  deleted_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
-- Compatibility view: "contactNotes" (camelCase alias, see views.sql)
-- RLS: contact_notes_select_role_based, contact_notes_insert_owner,
--      update_contact_notes_owner_or_privileged, delete_contact_notes_privileged_only
-- Triggers: set_updated_by_contact_notes, trigger_set_contact_notes_updated_by,
--           trigger_update_contact_notes_updated_at

-- --------------------------------------------------------------------------
-- 2. opportunity_notes
-- --------------------------------------------------------------------------
CREATE TABLE public.opportunity_notes (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id bigint NOT NULL REFERENCES public.opportunities(id) ON DELETE RESTRICT,
  sales_id       bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  created_by     bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  updated_by     bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  date           timestamptz DEFAULT now(),
  note           text,
  deleted_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
-- Compatibility view: "opportunityNotes" (camelCase alias, see views.sql)
-- RLS: opportunity_notes_select_role_based, opportunity_notes_insert_owner,
--      opportunity_notes_update_owner_or_privileged, delete_opportunity_notes_privileged_only
-- Triggers: set_updated_by_opportunity_notes, trigger_set_opportunity_notes_updated_by,
--           trigger_update_opportunity_notes_updated_at

-- --------------------------------------------------------------------------
-- 3. organization_notes
-- --------------------------------------------------------------------------
CREATE TABLE public.organization_notes (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  sales_id        bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  updated_by      bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  date            timestamptz DEFAULT now(),
  note            text,
  deleted_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
-- Compatibility view: "organizationNotes" (camelCase alias, see views.sql)
-- RLS: organization_notes_select_role_based, organization_notes_insert_owner,
--      organization_notes_update_owner_or_privileged, delete_organization_notes_privileged_only
-- Triggers: set_organization_notes_updated_by, trigger_update_organization_notes_updated_at
