-- ==========================================================================
-- Crispy CRM — Core Business Tables (Reference Snapshot)
-- Last synced: 2026-03-04 | Migrations: 20260214003329..20260303120000
-- WARNING: Read-only reference. Do NOT execute directly. Use migrations.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- 1. sales — Sales team members / user profiles
-- --------------------------------------------------------------------------
CREATE TABLE public.sales (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
  first_name    text,
  last_name     text,
  email         text,
  phone         text,
  avatar        text,
  avatar_url    text,
  role          public.user_role NOT NULL DEFAULT 'rep',
  is_admin      boolean GENERATED ALWAYS AS (role = 'admin') STORED,
  disabled      boolean NOT NULL DEFAULT false,
  deleted_at    timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
-- RLS: select_sales, update_sales, insert_sales, delete_sales, service_role_full_access
-- Triggers: keep_is_admin_synced, enforce_sales_column_restrictions_trigger,
--           audit_critical_sales, update_sales_updated_at
-- FK note: user_id ON DELETE SET NULL (migration 20260303100000)

-- --------------------------------------------------------------------------
-- 2. contacts — Customer/prospect contacts
-- --------------------------------------------------------------------------
CREATE TABLE public.contacts (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name                text NOT NULL,
  last_name                 text NOT NULL,
  name                      text GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
  email                     text,
  phone                     text,
  title                     text,
  department                text,
  address                   text,
  city                      text,
  state                     text,
  postal_code               text,
  country                   text,
  birthday                  date,
  linkedin_url              text,
  twitter_handle            text,
  job_title                 text,
  role                      public.contact_role,
  is_primary_decision_maker boolean DEFAULT false,
  purchase_influence        smallint,
  gender                    text,
  status                    text,
  first_seen                timestamptz,
  last_seen                 timestamptz,
  organization_id           bigint REFERENCES public.organizations(id) ON DELETE RESTRICT,
  manager_id                bigint REFERENCES public.contacts(id) ON DELETE SET NULL,
  sales_id                  bigint NOT NULL REFERENCES public.sales(id),
  secondary_sales_id        bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  created_by                bigint REFERENCES public.sales(id),
  updated_by                bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  tags                      text[],
  notes                     text,
  search_tsv                tsvector,
  deleted_at                timestamptz,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contacts_different_managers
    CHECK (sales_id IS NULL OR secondary_sales_id IS NULL OR sales_id != secondary_sales_id)
);
-- Indexes: idx_contacts_secondary_sales_id (partial, deleted_at IS NULL)
-- RLS: contacts_select_all, contacts_insert_owner, contacts_update_owner_or_privileged, delete_contacts
-- Triggers: trigger_update_contacts_search_tsv, set_updated_by_contacts,
--           protect_contacts_audit, audit_contacts_changes, audit_critical_contacts,
--           cascade_notes_on_contact_delete, trigger_log_contact_org_linked/unlinked,
--           update_contacts_updated_at

-- --------------------------------------------------------------------------
-- 3. organizations — Organizations (operators, distributors, principals)
-- --------------------------------------------------------------------------
CREATE TABLE public.organizations (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    text NOT NULL,
  website                 text,
  phone                   text,
  email                   text,
  linkedin_url            text,
  address                 text,
  city                    text,
  state                   text,
  zip                     text,
  postal_code             text,
  country                 text DEFAULT 'US',
  description             text,
  tags                    text[],
  notes                   text,
  organization_type       public.organization_type,
  org_scope               text,
  is_operating_entity     boolean DEFAULT true,
  status                  text,
  status_reason           text,
  needs_review            text,
  territory               text,
  cuisine                 text,
  priority                text,
  employee_count          integer,
  playbook_category_id    bigint REFERENCES public.segments(id) ON DELETE SET NULL,
  parent_organization_id  bigint REFERENCES public.organizations(id),
  segment_id              bigint REFERENCES public.segments(id),
  sales_id                bigint REFERENCES public.sales(id),
  secondary_sales_id      bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  created_by              bigint REFERENCES public.sales(id),
  updated_by              bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  search_tsv              tsvector,
  deleted_at              timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT organizations_different_managers
    CHECK (sales_id IS NULL OR secondary_sales_id IS NULL OR sales_id != secondary_sales_id),
  CONSTRAINT chk_no_self_parent CHECK (id != parent_organization_id)
);
-- Unique: organizations_name_unique_idx on lower(name) WHERE deleted_at IS NULL
-- Indexes: idx_organizations_secondary_sales_id (partial, deleted_at IS NULL)
-- RLS: organizations_select_all, organizations_insert_owner,
--      organizations_update_role_based, organizations_delete_owner_or_admin
-- Triggers: trigger_update_organizations_search_tsv, set_updated_by_organizations,
--           protect_organizations_audit, audit_organizations_changes,
--           audit_critical_organizations, cascade_notes_on_organization_delete,
--           check_organization_cycle, check_parent_deletion, prevent_parent_deletion,
--           prevent_org_delete_with_active_opps, set_default_segment_id_trigger,
--           update_organizations_updated_at

-- --------------------------------------------------------------------------
-- 4. opportunities — Sales deals/pipeline
-- --------------------------------------------------------------------------
CREATE TABLE public.opportunities (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                        text NOT NULL,
  stage                       public.opportunity_stage NOT NULL DEFAULT 'new_lead',
  status                      public.opportunity_status DEFAULT 'active',
  priority                    public.opportunity_priority DEFAULT 'medium',
  index                       integer,
  campaign                    text,
  description                 text,
  win_reason                  text,
  loss_reason                 text,
  competition                 text,
  decision_criteria           text,
  lead_source                 text,
  next_action                 text,
  next_action_date            timestamptz,
  estimated_close_date        date,
  actual_close_date           date,
  stage_manual                boolean,
  status_manual               boolean,
  contact_ids                 bigint[],
  tags                        text[],
  principal_organization_id   bigint REFERENCES public.organizations(id) ON DELETE RESTRICT,
  customer_organization_id    bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  distributor_organization_id bigint REFERENCES public.organizations(id) ON DELETE SET NULL,
  primary_contact_id          bigint REFERENCES public.contacts(id) ON DELETE SET NULL,
  account_manager_id          bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  opportunity_owner_id        bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  created_by                  bigint REFERENCES public.sales(id),
  updated_by                  bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  related_opportunity_id      bigint REFERENCES public.opportunities(id),
  founding_interaction_id     bigint REFERENCES public.activities(id) ON DELETE SET NULL,
  search_tsv                  tsvector,
  stage_changed_at            timestamptz,
  version                     integer NOT NULL DEFAULT 0,
  deleted_at                  timestamptz,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now()
);
-- RLS: opportunities_select_all, opportunities_update_dual_ownership,
--      insert_opportunities, delete_opportunities (admin only)
-- Triggers: trigger_update_opportunities_search_tsv, set_updated_by_opportunities,
--           protect_opportunities_audit, audit_opportunities_changes,
--           audit_critical_opportunities, cascade_notes_on_opportunity_delete,
--           opportunities_version_increment, trigger_update_opportunity_stage_changed_at,
--           trg_validate_opportunity_closure, enforce_related_opportunity_principal,
--           trigger_set_opportunity_owner_defaults, trigger_log_opportunity_created,
--           trigger_log_opportunity_archived, trigger_log_opportunity_stage_change,
--           update_opportunities_updated_at

-- --------------------------------------------------------------------------
-- 5. activities — Unified activities + tasks (STI pattern)
-- --------------------------------------------------------------------------
CREATE TABLE public.activities (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type              text,
  subject           text,
  description       text,
  activity_type     public.activity_type NOT NULL,
  activity_date     timestamptz NOT NULL DEFAULT now(),
  duration_minutes  integer,
  notes             text,
  outcome           text,
  sentiment         public.sentiment_type,
  sample_status     public.sample_status_type,
  campaign          text,
  follow_up_required boolean DEFAULT false,
  follow_up_date    timestamptz,
  -- Ownership
  sales_id          bigint NOT NULL REFERENCES public.sales(id),
  created_by        bigint REFERENCES public.sales(id),
  updated_by        bigint REFERENCES public.sales(id),
  -- Relations
  contact_id        bigint REFERENCES public.contacts(id) ON DELETE RESTRICT,
  organization_id   bigint REFERENCES public.organizations(id) ON DELETE SET NULL,
  opportunity_id    bigint REFERENCES public.opportunities(id) ON DELETE SET NULL,
  -- Task-specific fields (STI: populated when activity_type = 'task')
  due_date          timestamptz,
  reminder_date     timestamptz,
  completed         boolean DEFAULT false,
  completed_at      timestamptz,
  priority          text,
  task_type         text,
  related_task_id   bigint REFERENCES public.activities(id) ON DELETE SET NULL,
  snoozed_until     timestamptz,
  snooze_until      timestamptz,
  overdue_notified_at timestamptz,
  -- Timestamps
  deleted_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
-- Indexes: idx_activities_opportunity_last_activity (opportunity_id, activity_date DESC)
-- RLS: activities_select, activities_insert, activities_update,
--      activities_delete, activities_service_role
-- Triggers: trigger_set_activity_created_by, cascade_activity_contact_trigger,
--           trigger_validate_activity_consistency, protect_activities_audit,
--           trigger_set_founding_interaction, trigger_log_task_completed,
--           update_activities_updated_at

-- --------------------------------------------------------------------------
-- 6. products — Product catalog (principal's products)
-- --------------------------------------------------------------------------
CREATE TABLE public.products (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             text NOT NULL,
  category         text,
  description      text,
  sku              text,
  unit             text,
  msrp             numeric,
  status           text DEFAULT 'active',
  principal_id     bigint REFERENCES public.organizations(id) ON DELETE RESTRICT,
  created_by       bigint REFERENCES public.sales(id),
  updated_by       bigint REFERENCES public.sales(id),
  search_tsv       tsvector,
  deleted_at       timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
-- RLS: select_products, products_insert_privileged, products_update_privileged, delete_products
-- Triggers: products_search_update, protect_products_audit,
--           set_updated_by_products, update_products_updated_at
