-- ==========================================================================
-- Crispy CRM — Junction / Association Tables (Reference Snapshot)
-- Last synced: 2026-03-04 | Migrations: 20260214003329..20260303120000
-- WARNING: Read-only reference. Do NOT execute directly. Use migrations.
-- ==========================================================================

-- --------------------------------------------------------------------------
-- 1. opportunity_contacts — Opportunities <-> Contacts
-- --------------------------------------------------------------------------
CREATE TABLE public.opportunity_contacts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id bigint NOT NULL REFERENCES public.opportunities(id) ON DELETE RESTRICT,
  contact_id     bigint NOT NULL REFERENCES public.contacts(id) ON DELETE RESTRICT,
  deleted_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (opportunity_id, contact_id)  -- partial: WHERE deleted_at IS NULL
);
-- RLS: opportunity_contacts_select_through_opportunities, insert/update/delete (ownership via opportunity)

-- --------------------------------------------------------------------------
-- 2. opportunity_participants — Opportunities <-> Organizations (with role)
-- --------------------------------------------------------------------------
CREATE TABLE public.opportunity_participants (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id  bigint NOT NULL REFERENCES public.opportunities(id) ON DELETE RESTRICT,
  organization_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  role            text,
  created_by      bigint REFERENCES public.sales(id),
  deleted_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
-- RLS: opportunity_participants_select_policy, insert_validated, update_validated, delete_policy
-- Triggers: trigger_set_opportunity_participant_created_by,
--           trigger_validate_opportunity_participants, update_opportunity_participants_updated_at

-- --------------------------------------------------------------------------
-- 3. opportunity_products — Opportunities <-> Products (denormalized snapshot)
-- --------------------------------------------------------------------------
CREATE TABLE public.opportunity_products (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_id       bigint NOT NULL REFERENCES public.opportunities(id) ON DELETE RESTRICT,
  product_id_reference bigint REFERENCES public.products(id) ON DELETE RESTRICT,
  product_name         text,
  product_category     text,
  product_sku          text,
  quantity             numeric,
  unit_price           numeric,
  notes                text,
  created_by           bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  deleted_at           timestamptz,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
-- RLS: opportunity_products_select_all, insert/update/delete_authenticated
-- Triggers: set_opportunity_products_updated_at

-- --------------------------------------------------------------------------
-- 4. organization_distributors — Organizations <-> Distributors
-- --------------------------------------------------------------------------
CREATE TABLE public.organization_distributors (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  distributor_id  bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  is_primary      boolean DEFAULT false,
  created_by      bigint REFERENCES public.sales(id),
  deleted_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
-- Unique: idx_organization_one_primary_distributor (organization_id WHERE is_primary AND deleted_at IS NULL)
-- RLS: authenticated_select/insert/update/delete_organization_distributors
-- Triggers: update_organization_distributors_updated_at

-- --------------------------------------------------------------------------
-- 5. product_distributors — Products <-> Distributors (pricing/status)
-- --------------------------------------------------------------------------
CREATE TABLE public.product_distributors (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id         bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  distributor_id     bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  status             text DEFAULT 'active',
  vendor_item_number text,
  unit_cost          numeric,
  notes              text,
  deleted_at         timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
-- RLS: product_distributors_select/insert/update/delete_dual_auth, service_role_bypass
-- Triggers: update_product_distributors_updated_at

-- --------------------------------------------------------------------------
-- 6. product_distributor_authorizations — Product-level authorization overrides
-- --------------------------------------------------------------------------
CREATE TABLE public.product_distributor_authorizations (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  distributor_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  is_authorized  boolean NOT NULL DEFAULT true,
  notes          text,
  created_by     bigint REFERENCES public.sales(id),
  deleted_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
-- RLS: authenticated_select/insert/update/delete_product_distributor_authorizations
-- Triggers: update_product_distributor_authorizations_updated_at

-- --------------------------------------------------------------------------
-- 7. distributor_principal_authorizations — Distributor-level principal authorizations
-- --------------------------------------------------------------------------
CREATE TABLE public.distributor_principal_authorizations (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  distributor_id bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  principal_id   bigint NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  is_authorized  boolean NOT NULL DEFAULT true,
  territory      text,
  notes          text,
  created_by     bigint REFERENCES public.sales(id),
  deleted_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
-- RLS: authenticated_select/insert/update/delete_distributor_principal_authorizations
-- Triggers: update_distributor_principal_authorizations_updated_at

-- --------------------------------------------------------------------------
-- 8. interaction_participants — Activities <-> Contacts (multi-participant)
-- --------------------------------------------------------------------------
CREATE TABLE public.interaction_participants (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id     bigint NOT NULL REFERENCES public.activities(id) ON DELETE RESTRICT,
  contact_id      bigint REFERENCES public.contacts(id),
  organization_id bigint REFERENCES public.organizations(id) ON DELETE SET NULL,
  created_by      bigint REFERENCES public.sales(id),
  deleted_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
-- RLS: interaction_participants_select_policy, insert_owner, update_policy, delete_policy
-- Triggers: trigger_set_interaction_participant_created_by

-- --------------------------------------------------------------------------
-- 9. product_features — Product feature attributes
-- --------------------------------------------------------------------------
CREATE TABLE public.product_features (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id  bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  name        text NOT NULL,
  value       text,
  created_by  bigint REFERENCES public.sales(id) ON DELETE SET NULL,
  deleted_at  timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
-- RLS: authenticated view, admins insert/update/delete
-- Triggers: set_product_features_updated_at
