/**
 * SCIP Query Utilities for the Discovery System
 *
 * This module provides utilities to query SCIP (Source Code Intelligence Protocol)
 * index files generated by scip-typescript.
 *
 * Usage:
 *   import { loadIndex, findHooks, getReferences } from './scip/index.js';
 *   const index = await loadIndex('.claude/state/index.scip');
 *   const hooks = findHooks(index);
 */

export {
  // Types
  type Index,
  type Document,
  type Occurrence,
  type SymbolInformation,
  type OccurrenceLocation,
  // Enums
  SymbolRole,
  // Functions
  loadIndex,
  loadIndexSync,
  findSymbolsByPattern,
  findHooks,
  getReferences,
  getDefinition,
  getSymbolsInFile,
  getDocument,
  getIndexStats,
} from "./query.js";
