// Generated TypeScript types for Supabase database
// Generated at: 2025-10-09T02:46:17.796Z

export interface Database {
  public: {
    Tables: {
      activities: {
        Row: {
          id: number;
          activity_type: any;
          type: any;
          subject: string;
          description: string | null;
          activity_date: string | null;
          duration_minutes: number | null;
          contact_id: number | null;
          organization_id: number | null;
          opportunity_id: number | null;
          follow_up_required: boolean | null;
          follow_up_date: string | null;
          follow_up_notes: string | null;
          outcome: string | null;
          sentiment: string | null;
          attachments: any[] | null;
          location: string | null;
          attendees: any[] | null;
          tags: any[] | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: number;
          activity_type: any;
          type: any;
          subject: string;
          description?: string | null;
          activity_date?: string | null;
          duration_minutes?: number | null;
          contact_id?: number | null;
          organization_id?: number | null;
          opportunity_id?: number | null;
          follow_up_required?: boolean | null;
          follow_up_date?: string | null;
          follow_up_notes?: string | null;
          outcome?: string | null;
          sentiment?: string | null;
          attachments?: any[] | null;
          location?: string | null;
          attendees?: any[] | null;
          tags?: any[] | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: number;
          activity_type?: any;
          type?: any;
          subject?: string;
          description?: string | null;
          activity_date?: string | null;
          duration_minutes?: number | null;
          contact_id?: number | null;
          organization_id?: number | null;
          opportunity_id?: number | null;
          follow_up_required?: boolean | null;
          follow_up_date?: string | null;
          follow_up_notes?: string | null;
          outcome?: string | null;
          sentiment?: string | null;
          attachments?: any[] | null;
          location?: string | null;
          attendees?: any[] | null;
          tags?: any[] | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
      };
      contactNotes: {
        Row: {
          id: number;
          contact_id: number;
          text: string;
          attachments: any[] | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          date: string;
        };
        Insert: {
          id?: number;
          contact_id: number;
          text: string;
          attachments?: any[] | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          date?: string;
        };
        Update: {
          id?: number;
          contact_id?: number;
          text?: string;
          attachments?: any[] | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          date?: string;
        };
      };
      contact_organizations: {
        Row: {
          id: number;
          contact_id: number;
          organization_id: number;
          is_primary: boolean | null;
          is_primary_decision_maker: boolean | null;
          relationship_start_date: string | null;
          relationship_end_date: string | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: number;
          contact_id: number;
          organization_id: number;
          is_primary?: boolean | null;
          is_primary_decision_maker?: boolean | null;
          relationship_start_date?: string | null;
          relationship_end_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: number;
          contact_id?: number;
          organization_id?: number;
          is_primary?: boolean | null;
          is_primary_decision_maker?: boolean | null;
          relationship_start_date?: string | null;
          relationship_end_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
      };
      contact_preferred_principals: {
        Row: {
          id: number;
          contact_id: number;
          principal_organization_id: number;
          advocacy_strength: number | null;
          last_interaction_date: string | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: number;
          contact_id: number;
          principal_organization_id: number;
          advocacy_strength?: number | null;
          last_interaction_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: number;
          contact_id?: number;
          principal_organization_id?: number;
          advocacy_strength?: number | null;
          last_interaction_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
      };
      contacts: {
        Row: {
          id: number;
          name: string;
          first_name: string | null;
          last_name: string | null;
          email: any | null;
          phone: any | null;
          title: string | null;
          department: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          birthday: string | null;
          linkedin_url: string | null;
          twitter_handle: string | null;
          notes: string | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
          search_tsv: string | null;
          first_seen: string | null;
          last_seen: string | null;
          gender: string | null;
          tags: any[] | null;
          organization_id: number | null;
        };
        Insert: {
          id?: number;
          name: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: any | null;
          phone?: any | null;
          title?: string | null;
          department?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          birthday?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          first_seen?: string | null;
          last_seen?: string | null;
          gender?: string | null;
          tags?: any[] | null;
          organization_id?: number | null;
        };
        Update: {
          id?: number;
          name?: string;
          first_name?: string | null;
          last_name?: string | null;
          email?: any | null;
          phone?: any | null;
          title?: string | null;
          department?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          birthday?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          first_seen?: string | null;
          last_seen?: string | null;
          gender?: string | null;
          tags?: any[] | null;
          organization_id?: number | null;
        };
      };
      contacts_summary: {
        Row: {
          id: number | null;
          name: string | null;
          first_name: string | null;
          last_name: string | null;
          email: any | null;
          phone: any | null;
          title: string | null;
          department: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          birthday: string | null;
          linkedin_url: string | null;
          twitter_handle: string | null;
          notes: string | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
          search_tsv: string | null;
          first_seen: string | null;
          last_seen: string | null;
          gender: string | null;
          tags: any[] | null;
          organization_id: number | null;
          company_name: string | null;
        };
        Insert: {
          id?: number | null;
          name?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: any | null;
          phone?: any | null;
          title?: string | null;
          department?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          birthday?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          first_seen?: string | null;
          last_seen?: string | null;
          gender?: string | null;
          tags?: any[] | null;
          organization_id?: number | null;
          company_name?: string | null;
        };
        Update: {
          id?: number | null;
          name?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: any | null;
          phone?: any | null;
          title?: string | null;
          department?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          birthday?: string | null;
          linkedin_url?: string | null;
          twitter_handle?: string | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          first_seen?: string | null;
          last_seen?: string | null;
          gender?: string | null;
          tags?: any[] | null;
          organization_id?: number | null;
          company_name?: string | null;
        };
      };
      interaction_participants: {
        Row: {
          id: number;
          activity_id: number;
          contact_id: number | null;
          organization_id: number | null;
          role: string | null;
          notes: string | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          activity_id: number;
          contact_id?: number | null;
          organization_id?: number | null;
          role?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          activity_id?: number;
          contact_id?: number | null;
          organization_id?: number | null;
          role?: string | null;
          notes?: string | null;
          created_at?: string | null;
        };
      };
      migration_history: {
        Row: {
          id: number;
          phase_number: string;
          phase_name: string;
          status: string;
          started_at: string | null;
          completed_at: string | null;
          error_message: string | null;
          rollback_sql: string | null;
          rows_affected: number | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          phase_number: string;
          phase_name: string;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          rollback_sql?: string | null;
          rows_affected?: number | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          phase_number?: string;
          phase_name?: string;
          status?: string;
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          rollback_sql?: string | null;
          rows_affected?: number | null;
          created_at?: string | null;
        };
      };
      opportunities: {
        Row: {
          id: number;
          name: string;
          description: string | null;
          stage: any | null;
          status: any | null;
          priority: any | null;
          index: number | null;
          estimated_close_date: string | null;
          actual_close_date: string | null;
          customer_organization_id: number | null;
          principal_organization_id: number | null;
          distributor_organization_id: number | null;
          founding_interaction_id: number | null;
          stage_manual: boolean | null;
          status_manual: boolean | null;
          next_action: string | null;
          next_action_date: string | null;
          competition: string | null;
          decision_criteria: string | null;
          contact_ids: any[] | null;
          opportunity_owner_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
          search_tsv: string | null;
          tags: any[] | null;
          account_manager_id: number | null;
          lead_source: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          description?: string | null;
          stage?: any | null;
          status?: any | null;
          priority?: any | null;
          index?: number | null;
          estimated_close_date?: string | null;
          actual_close_date?: string | null;
          customer_organization_id?: number | null;
          principal_organization_id?: number | null;
          distributor_organization_id?: number | null;
          founding_interaction_id?: number | null;
          stage_manual?: boolean | null;
          status_manual?: boolean | null;
          next_action?: string | null;
          next_action_date?: string | null;
          competition?: string | null;
          decision_criteria?: string | null;
          contact_ids?: any[] | null;
          opportunity_owner_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          tags?: any[] | null;
          account_manager_id?: number | null;
          lead_source?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          description?: string | null;
          stage?: any | null;
          status?: any | null;
          priority?: any | null;
          index?: number | null;
          estimated_close_date?: string | null;
          actual_close_date?: string | null;
          customer_organization_id?: number | null;
          principal_organization_id?: number | null;
          distributor_organization_id?: number | null;
          founding_interaction_id?: number | null;
          stage_manual?: boolean | null;
          status_manual?: boolean | null;
          next_action?: string | null;
          next_action_date?: string | null;
          competition?: string | null;
          decision_criteria?: string | null;
          contact_ids?: any[] | null;
          opportunity_owner_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          tags?: any[] | null;
          account_manager_id?: number | null;
          lead_source?: string | null;
        };
      };
      opportunityNotes: {
        Row: {
          id: number;
          opportunity_id: number;
          text: string;
          attachments: any[] | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          date: string;
        };
        Insert: {
          id?: number;
          opportunity_id: number;
          text: string;
          attachments?: any[] | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          date?: string;
        };
        Update: {
          id?: number;
          opportunity_id?: number;
          text?: string;
          attachments?: any[] | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          date?: string;
        };
      };
      opportunity_participants: {
        Row: {
          id: number;
          opportunity_id: number;
          organization_id: number;
          role: string;
          is_primary: boolean | null;
          commission_rate: number | null;
          territory: string | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: number;
          opportunity_id: number;
          organization_id: number;
          role: string;
          is_primary?: boolean | null;
          commission_rate?: number | null;
          territory?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: number;
          opportunity_id?: number;
          organization_id?: number;
          role?: string;
          is_primary?: boolean | null;
          commission_rate?: number | null;
          territory?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
        };
      };
      organizations: {
        Row: {
          id: number;
          name: string;
          organization_type: any | null;
          is_principal: boolean | null;
          is_distributor: boolean | null;
          parent_organization_id: number | null;
          priority: string | null;
          website: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          logo_url: string | null;
          linkedin_url: string | null;
          annual_revenue: number | null;
          employee_count: number | null;
          founded_year: number | null;
          notes: string | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          deleted_at: string | null;
          import_session_id: string | null;
          search_tsv: string | null;
          context_links: any | null;
          description: string | null;
          tax_identifier: string | null;
          segment_id: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          organization_type?: any | null;
          is_principal?: boolean | null;
          is_distributor?: boolean | null;
          parent_organization_id?: number | null;
          priority?: string | null;
          website?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          linkedin_url?: string | null;
          annual_revenue?: number | null;
          employee_count?: number | null;
          founded_year?: number | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          import_session_id?: string | null;
          search_tsv?: string | null;
          context_links?: any | null;
          description?: string | null;
          tax_identifier?: string | null;
          segment_id?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          organization_type?: any | null;
          is_principal?: boolean | null;
          is_distributor?: boolean | null;
          parent_organization_id?: number | null;
          priority?: string | null;
          website?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          logo_url?: string | null;
          linkedin_url?: string | null;
          annual_revenue?: number | null;
          employee_count?: number | null;
          founded_year?: number | null;
          notes?: string | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          deleted_at?: string | null;
          import_session_id?: string | null;
          search_tsv?: string | null;
          context_links?: any | null;
          description?: string | null;
          tax_identifier?: string | null;
          segment_id?: string | null;
        };
      };
      organizations_summary: {
        Row: {
          id: number | null;
          name: string | null;
          organization_type: any | null;
          is_principal: boolean | null;
          is_distributor: boolean | null;
          priority: string | null;
          segment_id: string | null;
          annual_revenue: number | null;
          employee_count: number | null;
          phone: string | null;
          website: string | null;
          postal_code: string | null;
          city: string | null;
          state: string | null;
          description: string | null;
          created_at: string | null;
          nb_opportunities: number | null;
          nb_contacts: number | null;
          last_opportunity_activity: string | null;
        };
        Insert: {
          id?: number | null;
          name?: string | null;
          organization_type?: any | null;
          is_principal?: boolean | null;
          is_distributor?: boolean | null;
          priority?: string | null;
          segment_id?: string | null;
          annual_revenue?: number | null;
          employee_count?: number | null;
          phone?: string | null;
          website?: string | null;
          postal_code?: string | null;
          city?: string | null;
          state?: string | null;
          description?: string | null;
          created_at?: string | null;
          nb_opportunities?: number | null;
          nb_contacts?: number | null;
          last_opportunity_activity?: string | null;
        };
        Update: {
          id?: number | null;
          name?: string | null;
          organization_type?: any | null;
          is_principal?: boolean | null;
          is_distributor?: boolean | null;
          priority?: string | null;
          segment_id?: string | null;
          annual_revenue?: number | null;
          employee_count?: number | null;
          phone?: string | null;
          website?: string | null;
          postal_code?: string | null;
          city?: string | null;
          state?: string | null;
          description?: string | null;
          created_at?: string | null;
          nb_opportunities?: number | null;
          nb_contacts?: number | null;
          last_opportunity_activity?: string | null;
        };
      };
      product_catalog: {
        Row: {
          id: number | null;
          principal_id: number | null;
          name: string | null;
          description: string | null;
          sku: string | null;
          category: any | null;
          subcategory: string | null;
          brand: string | null;
          cost_per_unit: number | null;
          list_price: number | null;
          status: any | null;
          certifications: any[] | null;
          allergens: any[] | null;
          ingredients: string | null;
          nutritional_info: any | null;
          marketing_description: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          updated_by: number | null;
          deleted_at: string | null;
          search_tsv: string | null;
          tier_name: string | null;
          min_quantity: number | null;
          max_quantity: number | null;
          unit_price: number | null;
          discount_percent: number | null;
        };
        Insert: {
          id?: number | null;
          principal_id?: number | null;
          name?: string | null;
          description?: string | null;
          sku?: string | null;
          category?: any | null;
          subcategory?: string | null;
          brand?: string | null;
          cost_per_unit?: number | null;
          list_price?: number | null;
          status?: any | null;
          certifications?: any[] | null;
          allergens?: any[] | null;
          ingredients?: string | null;
          nutritional_info?: any | null;
          marketing_description?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          updated_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          tier_name?: string | null;
          min_quantity?: number | null;
          max_quantity?: number | null;
          unit_price?: number | null;
          discount_percent?: number | null;
        };
        Update: {
          id?: number | null;
          principal_id?: number | null;
          name?: string | null;
          description?: string | null;
          sku?: string | null;
          category?: any | null;
          subcategory?: string | null;
          brand?: string | null;
          cost_per_unit?: number | null;
          list_price?: number | null;
          status?: any | null;
          certifications?: any[] | null;
          allergens?: any[] | null;
          ingredients?: string | null;
          nutritional_info?: any | null;
          marketing_description?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          updated_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          tier_name?: string | null;
          min_quantity?: number | null;
          max_quantity?: number | null;
          unit_price?: number | null;
          discount_percent?: number | null;
        };
      };
      product_category_hierarchy: {
        Row: {
          id: number;
          category_name: string;
          parent_category_id: number | null;
          category_path: string | null;
          level: number;
          display_order: number | null;
          icon: string | null;
          description: string | null;
          attributes: any | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          category_name: string;
          parent_category_id?: number | null;
          category_path?: string | null;
          level?: number;
          display_order?: number | null;
          icon?: string | null;
          description?: string | null;
          attributes?: any | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          category_name?: string;
          parent_category_id?: number | null;
          category_path?: string | null;
          level?: number;
          display_order?: number | null;
          icon?: string | null;
          description?: string | null;
          attributes?: any | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      product_distributor_authorizations: {
        Row: {
          id: number;
          product_id: number;
          distributor_id: number;
          is_authorized: boolean | null;
          authorization_date: string | null;
          expiration_date: string | null;
          special_pricing: any | null;
          territory_restrictions: any[] | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          distributor_id: number;
          is_authorized?: boolean | null;
          authorization_date?: string | null;
          expiration_date?: string | null;
          special_pricing?: any | null;
          territory_restrictions?: any[] | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          distributor_id?: number;
          is_authorized?: boolean | null;
          authorization_date?: string | null;
          expiration_date?: string | null;
          special_pricing?: any | null;
          territory_restrictions?: any[] | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
      };
      product_features: {
        Row: {
          id: number;
          product_id: number;
          feature_name: string;
          feature_value: string | null;
          display_order: number | null;
          is_highlighted: boolean | null;
          created_at: string | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          feature_name: string;
          feature_value?: string | null;
          display_order?: number | null;
          is_highlighted?: boolean | null;
          created_at?: string | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          feature_name?: string;
          feature_value?: string | null;
          display_order?: number | null;
          is_highlighted?: boolean | null;
          created_at?: string | null;
        };
      };
      product_inventory: {
        Row: {
          id: number;
          product_id: number;
          warehouse_location: string | null;
          quantity_on_hand: number | null;
          quantity_committed: number | null;
          quantity_available: number | null;
          reorder_point: number | null;
          reorder_quantity: number | null;
          last_restock_date: string | null;
          next_restock_date: string | null;
          lot_numbers: any | null;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          warehouse_location?: string | null;
          quantity_on_hand?: number | null;
          quantity_committed?: number | null;
          quantity_available?: number | null;
          reorder_point?: number | null;
          reorder_quantity?: number | null;
          last_restock_date?: string | null;
          next_restock_date?: string | null;
          lot_numbers?: any | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          warehouse_location?: string | null;
          quantity_on_hand?: number | null;
          quantity_committed?: number | null;
          quantity_available?: number | null;
          reorder_point?: number | null;
          reorder_quantity?: number | null;
          last_restock_date?: string | null;
          next_restock_date?: string | null;
          lot_numbers?: any | null;
          updated_at?: string | null;
        };
      };
      product_pricing_models: {
        Row: {
          id: number;
          product_id: number;
          model_type: any | null;
          base_price: number | null;
          min_price: number | null;
          max_price: number | null;
          pricing_rules: any | null;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          model_type?: any | null;
          base_price?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          pricing_rules?: any | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          model_type?: any | null;
          base_price?: number | null;
          min_price?: number | null;
          max_price?: number | null;
          pricing_rules?: any | null;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
      };
      product_pricing_tiers: {
        Row: {
          id: number;
          product_id: number;
          tier_name: string | null;
          min_quantity: number;
          max_quantity: number | null;
          unit_price: number;
          discount_percent: number | null;
          discount_amount: number | null;
          effective_date: string | null;
          expiration_date: string | null;
          notes: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
        };
        Insert: {
          id?: number;
          product_id: number;
          tier_name?: string | null;
          min_quantity: number;
          max_quantity?: number | null;
          unit_price: number;
          discount_percent?: number | null;
          discount_amount?: number | null;
          effective_date?: string | null;
          expiration_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
        Update: {
          id?: number;
          product_id?: number;
          tier_name?: string | null;
          min_quantity?: number;
          max_quantity?: number | null;
          unit_price?: number;
          discount_percent?: number | null;
          discount_amount?: number | null;
          effective_date?: string | null;
          expiration_date?: string | null;
          notes?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
        };
      };
      products: {
        Row: {
          id: number;
          principal_id: number;
          name: string;
          description: string | null;
          sku: string;
          category: any;
          subcategory: string | null;
          brand: string | null;
          cost_per_unit: number | null;
          list_price: number | null;
          status: any | null;
          certifications: any[] | null;
          allergens: any[] | null;
          ingredients: string | null;
          nutritional_info: any | null;
          marketing_description: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: number | null;
          updated_by: number | null;
          deleted_at: string | null;
          search_tsv: string | null;
          currency_code: string | null;
          unit_of_measure: string | null;
          minimum_order_quantity: number | null;
          manufacturer_part_number: string | null;
        };
        Insert: {
          id?: number;
          principal_id: number;
          name: string;
          description?: string | null;
          sku: string;
          category: any;
          subcategory?: string | null;
          brand?: string | null;
          cost_per_unit?: number | null;
          list_price?: number | null;
          status?: any | null;
          certifications?: any[] | null;
          allergens?: any[] | null;
          ingredients?: string | null;
          nutritional_info?: any | null;
          marketing_description?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          updated_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          currency_code?: string | null;
          unit_of_measure?: string | null;
          minimum_order_quantity?: number | null;
          manufacturer_part_number?: string | null;
        };
        Update: {
          id?: number;
          principal_id?: number;
          name?: string;
          description?: string | null;
          sku?: string;
          category?: any;
          subcategory?: string | null;
          brand?: string | null;
          cost_per_unit?: number | null;
          list_price?: number | null;
          status?: any | null;
          certifications?: any[] | null;
          allergens?: any[] | null;
          ingredients?: string | null;
          nutritional_info?: any | null;
          marketing_description?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: number | null;
          updated_by?: number | null;
          deleted_at?: string | null;
          search_tsv?: string | null;
          currency_code?: string | null;
          unit_of_measure?: string | null;
          minimum_order_quantity?: number | null;
          manufacturer_part_number?: string | null;
        };
      };
      sales: {
        Row: {
          id: number;
          user_id: string | null;
          created_at: string | null;
          updated_at: string | null;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string | null;
          avatar_url: string | null;
          is_admin: boolean | null;
          deleted_at: string | null;
          disabled: boolean | null;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          is_admin?: boolean | null;
          deleted_at?: string | null;
          disabled?: boolean | null;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          is_admin?: boolean | null;
          deleted_at?: string | null;
          disabled?: boolean | null;
        };
      };
      segments: {
        Row: {
          id: string;
          name: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
          created_by?: string | null;
        };
      };
      tags: {
        Row: {
          id: number;
          name: string;
          color: string | null;
          description: string | null;
          usage_count: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: number;
          name: string;
          color?: string | null;
          description?: string | null;
          usage_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          color?: string | null;
          description?: string | null;
          usage_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      tasks: {
        Row: {
          id: number;
          title: string;
          description: string | null;
          due_date: string | null;
          reminder_date: string | null;
          completed: boolean | null;
          completed_at: string | null;
          priority: any | null;
          contact_id: number | null;
          opportunity_id: number | null;
          sales_id: number | null;
          created_at: string | null;
          updated_at: string | null;
          type: any | null;
        };
        Insert: {
          id?: number;
          title: string;
          description?: string | null;
          due_date?: string | null;
          reminder_date?: string | null;
          completed?: boolean | null;
          completed_at?: string | null;
          priority?: any | null;
          contact_id?: number | null;
          opportunity_id?: number | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          type?: any | null;
        };
        Update: {
          id?: number;
          title?: string;
          description?: string | null;
          due_date?: string | null;
          reminder_date?: string | null;
          completed?: boolean | null;
          completed_at?: string | null;
          priority?: any | null;
          contact_id?: number | null;
          opportunity_id?: number | null;
          sales_id?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          type?: any | null;
        };
      };
    };
  };
}
