---
title: components Feature
---
flowchart LR

  %% Components
  CreateFormFooter([CreateFormFooter])
  QuickAddTaskButton([QuickAddTaskButton])
  SampleStatusStepper([SampleStatusStepper])

  %% Functions
  getNextStatus[getNextStatus]
  getPreviousStatus[getPreviousStatus]
  isValidTransition[isValidTransition]
