---
title: contexts Feature
---
flowchart LR

  %% Components
  AppBrandingProvider([AppBrandingProvider])
  FormOptionsProvider([FormOptionsProvider])
  PipelineConfigProvider([PipelineConfigProvider])

  %% Hooks
  useAppBranding((useAppBranding))
  useFormOptions((useFormOptions))
  usePipelineConfig((usePipelineConfig))
