---
title: Crispy CRM Call Graph
---
flowchart LR

  %% Components
  ActivityCreate([ActivityCreate])
  HiddenActivityTypeField([HiddenActivityTypeField])
  ActivityFormContent([ActivityFormContent])
  ActivityEdit([ActivityEdit])
  ActivityEditForm([ActivityEditForm])
  ActivityInputs([ActivityInputs])
  ActivityList([ActivityList])
  ActivityListLayout([ActivityListLayout])
  ActivityListActions([ActivityListActions])
  ActivityListFilter([ActivityListFilter])
  ActivitySinglePage([ActivitySinglePage])
  QuickLogActivity([QuickLogActivity])
  QuickLogFormSkeleton([QuickLogFormSkeleton])
  LockedEntityDisplay([LockedEntityDisplay])
  QuickLogActivityDialog([QuickLogActivityDialog])
  ActivityTimelineEntry([ActivityTimelineEntry])
  ActivityListView([ActivityListView])
  ActivityCreateView([ActivityCreateView])
  ActivityEditView([ActivityEditView])
  ActivityLog([ActivityLog])
  ActivityLogContactCreated([ActivityLogContactCreated])
  ContactAvatar([ContactAvatar])
  ActivityLogContactNoteCreated([ActivityLogContactNoteCreated])
  ActivityLogIterator([ActivityLogIterator])
  ActivityItem([ActivityItem])
  ActivityLogNote([ActivityLogNote])
  ActivityLogOpportunityCreated([ActivityLogOpportunityCreated])
  ActivityLogOpportunityNoteCreated([ActivityLogOpportunityNoteCreated])
  ActivityLogOrganizationCreated([ActivityLogOrganizationCreated])
  StatusIndicator([StatusIndicator])
  MetricCard([MetricCard])
  HealthDashboard([HealthDashboard])
  CreateFormFooter([CreateFormFooter])
  QuickAddTaskButton([QuickAddTaskButton])
  SampleStatusStepper([SampleStatusStepper])
  ActivitiesTab([ActivitiesTab])
  Avatar([Avatar])
  ContactAdditionalDetails([ContactAdditionalDetails])
  ContactAside([ContactAside])
  PersonalInfoRow([PersonalInfoRow])
  ContactBadgeGroup([ContactBadgeGroup])
  ContactCompactForm([ContactCompactForm])
  ContactCreate([ContactCreate])
  ContactFormContent([ContactFormContent])
  ContactNameHeader([ContactNameHeader])
  ContactStatusHeader([ContactStatusHeader])
  ContactDetailsTab([ContactDetailsTab])
  ContactEdit([ContactEdit])
  ContactEditContent([ContactEditContent])
  ContactEmpty([ContactEmpty])
  ContactExportTemplateButton([ContactExportTemplateButton])
  ContactFormTutorial([ContactFormTutorial])
  ContactHierarchyBreadcrumb([ContactHierarchyBreadcrumb])
  ContactImportButton([ContactImportButton])
  ContactImportDialog([ContactImportDialog])
  ContactImportPreview([ContactImportPreview])
  ContactImportResult([ContactImportResult])
  ContactInputs([ContactInputs])
  ContactList([ContactList])
  ContactListLayout([ContactListLayout])
  ContactListActions([ContactListActions])
  ContactListFilter([ContactListFilter])
  ContactManagerInput([ContactManagerInput])
  ContactOptionRender([ContactOptionRender])
  ContactShow([ContactShow])
  ContactShowContent([ContactShowContent])
  ContactSlideOver([ContactSlideOver])
  LinkOpportunityModal([LinkOpportunityModal])
  OpportunitiesTab([OpportunitiesTab])
  SuggestedOpportunityCard([SuggestedOpportunityCard])
  ColoredBadge([ColoredBadge])
  TagsList([TagsList])
  TagsListEdit([TagsListEdit])
  UnlinkConfirmDialog([UnlinkConfirmDialog])
  ContactListView([ContactListView])
  ContactEditView([ContactEditView])
  ContactCreateView([ContactCreateView])
  ContactNotesTab([ContactNotesTab])
  AppBrandingProvider([AppBrandingProvider])
  FormOptionsProvider([FormOptionsProvider])
  PipelineConfigProvider([PipelineConfigProvider])
  DashboardTutorial([DashboardTutorial])
  PrincipalDashboardV3([PrincipalDashboardV3])
  ActivityFeedPanel([ActivityFeedPanel])
  ActivityTypeSection([ActivityTypeSection])
  TabSkeleton([TabSkeleton])
  DashboardTabPanel([DashboardTabPanel])
  EntityCombobox([EntityCombobox])
  FollowUpSection([FollowUpSection])
  KPICard([KPICard])
  KPISummaryRow([KPISummaryRow])
  QuickLogFormSkeleton([QuickLogFormSkeleton])
  LogActivityFAB([LogActivityFAB])
  QuickLogFormSkeleton([QuickLogFormSkeleton])
  MobileQuickActionBar([MobileQuickActionBar])
  MetricCard([MetricCard])
  MyPerformanceWidget([MyPerformanceWidget])
  PipelineDrillDownSheet([PipelineDrillDownSheet])
  OpportunityCard([OpportunityCard])
  MomentumIcon([MomentumIcon])
  PipelineTableRow([PipelineTableRow])
  PrincipalPipelineTable([PrincipalPipelineTable])
  SortableTableHead([SortableTableHead])
  MomentumFilterDropdown([MomentumFilterDropdown])
  EmptyState([EmptyState])
  QuickLogForm([QuickLogForm])
  SnoozePopover([SnoozePopover])
  TaskItemCard([TaskItemCard])
  TaskListSkeleton([TaskListSkeleton])
  TaskCompleteSheet([TaskCompleteSheet])
  TasksKanbanPanel([TasksKanbanPanel])
  CurrentSaleProvider([CurrentSaleProvider])

  %% Hooks
  useActivityLogContext((useActivityLogContext))
  useColumnMapping((useColumnMapping))
  useContactImport((useContactImport))
  useImportWizard((useImportWizard))
  usePapaParse((usePapaParse))
  useAppBranding((useAppBranding))
  useFormOptions((useFormOptions))
  usePipelineConfig((usePipelineConfig))
  useCurrentSale((useCurrentSale))
  useCurrentSaleDirect((useCurrentSaleDirect))
  useDebouncedSearch((useDebouncedSearch))
  useEntityData((useEntityData))
  useHybridSearch((useHybridSearch))
  useKPIMetrics((useKPIMetrics))

  %% Functions
  exporter[exporter]
  inferActivityTypeFromTitle[inferActivityTypeFromTitle]
  loadDraft[loadDraft]
  saveDraft[saveDraft]
  clearDraft[clearDraft]
  formatDateLabel[formatDateLabel]
  activityRecordRepresentation[activityRecordRepresentation]
  getStatusColor[getStatusColor]
  getStatusText[getStatusText]
  getNextStatus[getNextStatus]
  getPreviousStatus[getPreviousStatus]
  isValidTransition[isValidTransition]
  numericToLevel[numericToLevel]
  normalizeHeader[normalizeHeader]
  findCanonicalField[findCanonicalField]
  isFullNameColumn[isFullNameColumn]
  getUnmappedHeaders[getUnmappedHeaders]
  mapHeadersToFields[mapHeadersToFields]
  getHeaderMappingDescription[getHeaderMappingDescription]
  validateRequiredMappings[validateRequiredMappings]
  getAvailableFields[getAvailableFields]
  getAvailableFieldsWithLabels[getAvailableFieldsWithLabels]
  sanitizeForCSV[sanitizeForCSV]
  contactExporter[contactExporter]
  formatDateLabel[formatDateLabel]
  extractNewOrganizations[extractNewOrganizations]
  extractNewTags[extractNewTags]
  findOrganizationsWithoutContacts[findOrganizationsWithoutContacts]
  findContactsWithoutContactInfo[findContactsWithoutContactInfo]
  isOrganizationOnlyEntry[isOrganizationOnlyEntry]
  isContactWithoutContactInfo[isContactWithoutContactInfo]
  applyDataQualityTransformations[applyDataQualityTransformations]
  validateTransformedContacts[validateTransformedContacts]
  splitFullName[splitFullName]
  transformHeaders[transformHeaders]
  processCsvData[processCsvData]
  processCsvDataWithMappings[processCsvDataWithMappings]
  parseRawCsvData[parseRawCsvData]
  contactRecordRepresentation[contactRecordRepresentation]
  fetchRecordsWithCache[fetchRecordsWithCache]
  parseTags[parseTags]
  validateOrganizationNames[validateOrganizationNames]
  validateTagNames[validateTagNames]
  createInitialState[createInitialState]
  importWizardReducer[importWizardReducer]
  reduceIdleState[reduceIdleState]
  reduceFileSelectedState[reduceFileSelectedState]
  reduceParsingState[reduceParsingState]
  reducePreviewState[reducePreviewState]
  reduceImportingState[reduceImportingState]
  reduceCompleteState[reduceCompleteState]
  reduceErrorState[reduceErrorState]
  createWizardActions[createWizardActions]
  assertNever[assertNever]
  canSelectFile[canSelectFile]
  canStartImport[canStartImport]
  canCancel[canCancel]
  hasFile[hasFile]
  isTerminal[isTerminal]
  isProcessing[isProcessing]
  deriveWizardFlags[deriveWizardFlags]
  formatActivityType[formatActivityType]
  formatRelativeTime[formatRelativeTime]
  getInitials[getInitials]
  getDisplayName[getDisplayName]
  loadDraft[loadDraft]
  saveDraft[saveDraft]
  clearDraft[clearDraft]
  getDecayIndicatorColor[getDecayIndicatorColor]
  arePropsEqual[arePropsEqual]
  getTaskIcon[getTaskIcon]
  arePropsEqual[arePropsEqual]
  calculateTrend[calculateTrend]
  createMetric[createMetric]

  %% Render relationships
  ActivityCreate -->|render| ActivityFormContent
  ActivityFormContent -->|render| HiddenActivityTypeField
  ActivityFormContent -->|render| ActivitySinglePage
  ActivityEdit -->|render| ActivityEditForm
  ActivityEditForm -->|render| ActivityInputs
  ActivityInputs -->|render| ActivitySinglePage
  ActivityList -->|render| ActivityListActions
  ActivityList -->|render| ActivityListLayout
  ActivityListLayout -->|render| ActivityListFilter
  ActivityListLayout -->|render| ActivityListFilter
  ActivityListLayout -->|render| ActivityListFilter
  QuickLogActivityDialog -->|render| LockedEntityDisplay
  QuickLogActivityDialog -->|render| LockedEntityDisplay
  QuickLogActivityDialog -->|render| LockedEntityDisplay
  QuickLogActivityDialog -->|render| QuickLogFormSkeleton
  QuickLogActivityDialog -->|render| QuickLogForm
  ActivityLog -->|render| ActivityLogIterator
  ActivityLogContactCreated -->|render| Avatar
  ContactAvatar -->|render| Avatar
  ActivityLogContactNoteCreated -->|render| ActivityLogNote
  ActivityLogContactNoteCreated -->|render| ContactAvatar
  ActivityLogIterator -->|render| ActivityItem
  ActivityItem -->|render| ActivityLogOrganizationCreated
  ActivityItem -->|render| ActivityLogContactCreated
  ActivityItem -->|render| ActivityLogContactNoteCreated
  ActivityItem -->|render| ActivityLogOpportunityCreated
  ActivityItem -->|render| ActivityLogOpportunityNoteCreated
  ActivityLogOpportunityNoteCreated -->|render| ActivityLogNote
  HealthDashboard -->|render| StatusIndicator
  HealthDashboard -->|render| MetricCard
  HealthDashboard -->|render| MetricCard
  HealthDashboard -->|render| MetricCard
  HealthDashboard -->|render| MetricCard
  ActivitiesTab -->|render| ActivityTimelineEntry
  ActivitiesTab -->|render| QuickLogActivityDialog
  ContactAdditionalDetails -->|render| ContactManagerInput
  ContactAside -->|render| PersonalInfoRow
  ContactAside -->|render| PersonalInfoRow
  ContactAside -->|render| PersonalInfoRow
  ContactAside -->|render| TagsListEdit
  ContactCompactForm -->|render| Avatar
  ContactCompactForm -->|render| ContactAdditionalDetails
  ContactCreate -->|render| ContactFormContent
  ContactCreate -->|render| ContactFormTutorial
  ContactFormContent -->|render| ContactInputs
  ContactFormContent -->|render| CreateFormFooter
  ContactDetailsTab -->|render| ContactInputs
  ContactDetailsTab -->|render| Avatar
  ContactEdit -->|render| ContactEditContent
  ContactEditContent -->|render| ContactInputs
  ContactEditContent -->|render| ContactAside
  ContactEmpty -->|render| ContactImportButton
  ContactImportButton -->|render| ContactImportDialog
  ContactImportDialog -->|render| ContactImportPreview
  ContactImportDialog -->|render| ContactImportResult
  ContactInputs -->|render| ContactCompactForm
  ContactList -->|render| ContactListActions
  ContactList -->|render| ContactListLayout
  ContactList -->|render| ContactSlideOver
  ContactListLayout -->|render| ContactListFilter
  ContactListLayout -->|render| ContactEmpty
  ContactListLayout -->|render| ContactListFilter
  ContactListLayout -->|render| ContactListFilter
  ContactListLayout -->|render| Avatar
  ContactListLayout -->|render| ContactNameHeader
  ContactListLayout -->|render| ContactStatusHeader
  ContactOptionRender -->|render| Avatar
  ContactShow -->|render| ContactShowContent
  ContactShowContent -->|render| Avatar
  ContactShowContent -->|render| ActivitiesTab
  ContactShowContent -->|render| OpportunitiesTab
  ContactShowContent -->|render| ContactAside
  ContactSlideOver -->|render| ActivitiesTab
  ContactSlideOver -->|render| QuickAddTaskButton
  OpportunitiesTab -->|render| SuggestedOpportunityCard
  OpportunitiesTab -->|render| LinkOpportunityModal
  OpportunitiesTab -->|render| LinkOpportunityModal
  OpportunitiesTab -->|render| LinkOpportunityModal
  OpportunitiesTab -->|render| UnlinkConfirmDialog
  TagsList -->|render| ColoredBadge
  PrincipalDashboardV3 -->|render| KPISummaryRow
  PrincipalDashboardV3 -->|render| DashboardTabPanel
  PrincipalDashboardV3 -->|render| LogActivityFAB
  PrincipalDashboardV3 -->|render| MobileQuickActionBar
  PrincipalDashboardV3 -->|render| TaskCompleteSheet
  PrincipalDashboardV3 -->|render| DashboardTutorial
  ActivityFeedPanel -->|render| ActivityItem
  DashboardTabPanel -->|render| TabSkeleton
  DashboardTabPanel -->|render| PrincipalPipelineTable
  DashboardTabPanel -->|render| TabSkeleton
  DashboardTabPanel -->|render| TasksKanbanPanel
  DashboardTabPanel -->|render| TabSkeleton
  DashboardTabPanel -->|render| MyPerformanceWidget
  DashboardTabPanel -->|render| TabSkeleton
  DashboardTabPanel -->|render| ActivityFeedPanel
  KPISummaryRow -->|render| KPICard
  KPISummaryRow -->|render| KPICard
  KPISummaryRow -->|render| KPICard
  KPISummaryRow -->|render| KPICard
  LogActivityFAB -->|render| QuickLogFormSkeleton
  LogActivityFAB -->|render| QuickLogForm
  MobileQuickActionBar -->|render| QuickLogFormSkeleton
  MobileQuickActionBar -->|render| QuickLogForm
  MyPerformanceWidget -->|render| MetricCard
  MyPerformanceWidget -->|render| MetricCard
  MyPerformanceWidget -->|render| MetricCard
  MyPerformanceWidget -->|render| MetricCard
  PipelineDrillDownSheet -->|render| OpportunityCard
  PipelineTableRow -->|render| MomentumIcon
  PrincipalPipelineTable -->|render| MomentumFilterDropdown
  PrincipalPipelineTable -->|render| EmptyState
  PrincipalPipelineTable -->|render| SortableTableHead
  PrincipalPipelineTable -->|render| SortableTableHead
  PrincipalPipelineTable -->|render| SortableTableHead
  PrincipalPipelineTable -->|render| SortableTableHead
  PrincipalPipelineTable -->|render| SortableTableHead
  PrincipalPipelineTable -->|render| PipelineTableRow
  PrincipalPipelineTable -->|render| PipelineDrillDownSheet
  QuickLogForm -->|render| ActivityTypeSection
  QuickLogForm -->|render| EntityCombobox
  QuickLogForm -->|render| EntityCombobox
  QuickLogForm -->|render| EntityCombobox
  QuickLogForm -->|render| FollowUpSection
  TaskCompleteSheet -->|render| TaskListSkeleton
  TaskCompleteSheet -->|render| TaskItemCard

  %% Hook dependencies
  ActivityLogContactCreated -.->|hook| useActivityLogContext
  ActivityLogContactNoteCreated -.->|hook| useActivityLogContext
  ActivityLogOpportunityCreated -.->|hook| useActivityLogContext
  ActivityLogOpportunityNoteCreated -.->|hook| useActivityLogContext
  ActivityLogOrganizationCreated -.->|hook| useActivityLogContext
  ContactImportDialog -.->|hook| useContactImport
  ContactImportDialog -.->|hook| useImportWizard
  ContactImportDialog -.->|hook| useColumnMapping
  ContactImportDialog -.->|hook| usePapaParse
  KPISummaryRow -.->|hook| useKPIMetrics
  QuickLogForm -.->|hook| useCurrentSale
  QuickLogForm -.->|hook| useEntityData
  useCurrentSale -.->|hook| useCurrentSaleDirect
  useEntityData -.->|hook| useDebouncedSearch
  useEntityData -.->|hook| useDebouncedSearch
  useEntityData -.->|hook| useDebouncedSearch
  useKPIMetrics -.->|hook| useCurrentSale

  %% Function calls
  QuickLogActivity -->|call| inferActivityTypeFromTitle
  QuickLogActivityDialog -->|call| loadDraft
  QuickLogActivityDialog -->|call| loadDraft
  QuickLogActivityDialog -->|call| clearDraft
  QuickLogActivityDialog -->|call| saveDraft
  HealthDashboard -->|call| getStatusColor
  HealthDashboard -->|call| getStatusText
  ContactImportDialog -->|call| findOrganizationsWithoutContacts
  ContactImportDialog -->|call| findContactsWithoutContactInfo
  ContactImportDialog -->|call| findCanonicalField
  ContactImportDialog -->|call| isFullNameColumn
  ContactImportDialog -->|call| extractNewOrganizations
  ContactImportDialog -->|call| extractNewTags
  ContactImportDialog -->|call| findOrganizationsWithoutContacts
  ContactImportDialog -->|call| findContactsWithoutContactInfo
  ContactImportDialog -->|call| extractNewOrganizations
  ContactImportDialog -->|call| extractNewTags
  ContactImportDialog -->|call| assertNever
  ContactImportPreview -->|call| getAvailableFieldsWithLabels
  findCanonicalField -->|call| normalizeHeader
  isFullNameColumn -->|call| normalizeHeader
  getUnmappedHeaders -->|call| findCanonicalField
  getUnmappedHeaders -->|call| isFullNameColumn
  mapHeadersToFields -->|call| isFullNameColumn
  mapHeadersToFields -->|call| findCanonicalField
  getHeaderMappingDescription -->|call| isFullNameColumn
  getHeaderMappingDescription -->|call| findCanonicalField
  getAvailableFieldsWithLabels -->|call| getAvailableFields
  contactExporter -->|call| sanitizeForCSV
  findOrganizationsWithoutContacts -->|call| isOrganizationOnlyEntry
  findContactsWithoutContactInfo -->|call| isContactWithoutContactInfo
  applyDataQualityTransformations -->|call| isOrganizationOnlyEntry
  transformHeaders -->|call| mapHeadersToFields
  processCsvData -->|call| transformHeaders
  processCsvData -->|call| splitFullName
  processCsvDataWithMappings -->|call| splitFullName
  parseRawCsvData -->|call| processCsvData
  useColumnMapping -->|call| mapHeadersToFields
  useColumnMapping -->|call| processCsvDataWithMappings
  useContactImport -->|call| validateOrganizationNames
  useContactImport -->|call| fetchRecordsWithCache
  useContactImport -->|call| validateTagNames
  useContactImport -->|call| fetchRecordsWithCache
  useContactImport -->|call| applyDataQualityTransformations
  useContactImport -->|call| validateTransformedContacts
  useContactImport -->|call| isContactWithoutContactInfo
  useContactImport -->|call| parseTags
  useContactImport -->|call| parseTags
  importWizardReducer -->|call| createInitialState
  importWizardReducer -->|call| reduceIdleState
  importWizardReducer -->|call| reduceFileSelectedState
  importWizardReducer -->|call| reduceParsingState
  importWizardReducer -->|call| reducePreviewState
  importWizardReducer -->|call| reduceImportingState
  importWizardReducer -->|call| reduceCompleteState
  importWizardReducer -->|call| reduceErrorState
  importWizardReducer -->|call| assertNever
  reduceFileSelectedState -->|call| createInitialState
  reduceParsingState -->|call| createInitialState
  reducePreviewState -->|call| createInitialState
  reduceImportingState -->|call| createInitialState
  useImportWizard -->|call| createWizardActions
  useImportWizard -->|call| deriveWizardFlags
  deriveWizardFlags -->|call| hasFile
  deriveWizardFlags -->|call| isTerminal
  deriveWizardFlags -->|call| isProcessing
  usePapaParse -->|call| parseRawCsvData
  LogActivityFAB -->|call| loadDraft
  LogActivityFAB -->|call| clearDraft
  LogActivityFAB -->|call| saveDraft
  LogActivityFAB -->|call| loadDraft
  PipelineTableRow -->|call| getDecayIndicatorColor
  createMetric -->|call| calculateTrend
