-- Baseline Schema Migration
-- Generated: 2025-09-26
--
-- This migration represents the complete database schema as of this date.
-- It consolidates 65+ previous migrations into a single baseline.
--
-- IMPORTANT: This is the source of truth for the database schema moving forward.
-- All future migrations should build incrementally upon this baseline.
--
-- Engineering Constitution Compliance:
-- - Uses YYYYMMDDHHMMSS timestamp format
-- - No backward compatibility maintenance
-- - Single unified schema approach
-- - Database as source of truth

-- Note: This is a placeholder for the baseline schema.
-- The actual schema has been applied through the 65 migrations already in the database.
-- Future migrations will be tracked from this point forward.

-- Applied migrations as of baseline:
-- - Fresh CRM schema with organizations/opportunities terminology
-- - Junction tables for many-to-many relationships
-- - RLS policies with simple authenticated access
-- - Search vectors with GIN indexes
-- - Business logic functions (20+)
-- - Summary views for React Admin
-- - Removed tasks.archived_at column
-- - Added set_primary_organization() RPC function

-- The database is fully functional with:
-- - 24 core tables
-- - 85+ performance indexes
-- - Complete RLS coverage
-- - Trigger-based search vector updates
-- - Soft delete support via deleted_at