/**
 * Activities Resource Lifecycle Callbacks
 *
 * Resource-specific logic for activities using React Admin's withLifecycleCallbacks pattern.
 * Uses the createResourceCallbacks factory for standard soft-delete behavior.
 *
 * Key behaviors:
 * 1. Soft delete - Sets deleted_at instead of hard delete
 * 2. Filter cleaning - Adds soft delete filter by default
 * 3. Data transformation - Strips computed fields from joins before save
 * 4. Sample status preservation - Ensures type field is preserved for sample activities
 * 5. Task completion handling - Auto-sets completed_at timestamp (STI pattern)
 * 6. Snooze normalization - Ensures snooze_until is valid ISO date or null
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 *
 * Note: After STI migration, this handler serves BOTH regular activities AND tasks.
 * Tasks are distinguished by activity_type = 'task'.
 */

import {
  createResourceCallbacks,
  type ResourceCallbacks,
  type Transform,
  type TransformFn,
} from "./createResourceCallbacks";

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by views or JOINs with contacts/organizations/sales
 *
 * Includes both activity computed fields and task computed fields (STI pattern)
 */
export const COMPUTED_FIELDS = [
  // Activity computed fields
  "contact_name",
  "organization_name",
  "opportunity_name",
  // Task computed fields (after STI migration)
  "assignee_name",
  "assignee_email",
  "creator_name",
  // From priority_tasks view
  "customer_name",
  "principal_name",
  // From activities_summary view (principal org join)
  "principal_organization_id",
  "principal_organization_name",
  // Timeline computed fields
  "entry_type",
  "subtype",
  "entry_date",
  "task_status",
  "is_task",
  "is_overdue",
  "days_until_due",
] as const;

/**
 * Write transform to preserve critical fields during updates.
 *
 * FIX: When updating sample_status, ensure the 'type' field is preserved.
 * Without this, partial updates might lose the type='sample' value which
 * is required for sample_status validation to work correctly.
 *
 * This transform ensures that for sample activities:
 * - If sample_status is being set/updated, type must be 'sample'
 * - If type is missing from update data, it's preserved from existing record
 */
const preserveSampleTypeTransform: TransformFn = (data) => {
  // If sample_status is being set and type is not provided, ensure type consistency
  // The validation layer will handle rejecting sample_status on non-sample activities
  // This transform only ensures type is not accidentally lost during partial updates
  if (data.sample_status !== undefined && data.type === undefined) {
    // When sample_status is provided but type is not, assume it's a sample activity
    // The database already has type='sample' for this record, but partial updates
    // from some providers might not include unchanged fields.
    // We set type='sample' explicitly to ensure validation passes correctly.
    return {
      ...data,
      type: "sample",
    };
  }
  return data;
};

/**
 * Transform: Handle task completion timestamp (STI pattern)
 *
 * When completed flag changes:
 * - true → set completed_at to current timestamp
 * - false → clear completed_at
 *
 * Only applies to task activities (activity_type = 'task')
 */
const handleTaskCompletionTimestamp: Transform = {
  name: "handleTaskCompletionTimestamp",
  description: "Sets or clears completed_at based on completed flag for task activities",
  apply: (record) => {
    // Only modify if completed field is present and it's a task
    // Note: For new tasks, activity_type may be in the data
    const isTask =
      record.activity_type === "task" ||
      (record.due_date !== undefined && record.sales_id !== undefined);

    if (isTask && "completed" in record) {
      if (record.completed === true && !record.completed_at) {
        return {
          ...record,
          completed_at: new Date().toISOString(),
        };
      } else if (record.completed === false) {
        return {
          ...record,
          completed_at: null,
        };
      }
    }
    return record;
  },
};

/**
 * Transform: Normalize snooze_until field (STI pattern)
 *
 * Ensures snooze_until is either a valid ISO date or null.
 * Empty strings and invalid dates become null.
 *
 * Only applies to task activities.
 */
const normalizeTaskSnoozeUntil: Transform = {
  name: "normalizeTaskSnoozeUntil",
  description: "Normalizes snooze_until date field for task activities",
  apply: (record) => {
    if ("snooze_until" in record) {
      // Empty string or undefined becomes null
      if (!record.snooze_until) {
        return { ...record, snooze_until: null };
      }
      // Ensure it's a valid ISO date string
      const date = new Date(record.snooze_until as string);
      if (isNaN(date.getTime())) {
        return { ...record, snooze_until: null };
      }
      return { ...record, snooze_until: date.toISOString() };
    }
    return record;
  },
};

/**
 * Transform: Map task title to subject field (STI pattern)
 *
 * Tasks use 'title' in the UI but the unified activities table uses 'subject'.
 * This transform maps title → subject for task creates/updates.
 */
const mapTaskTitleToSubject: Transform = {
  name: "mapTaskTitleToSubject",
  description: "Maps task title field to activities subject field",
  apply: (record) => {
    // If 'title' is provided (from task forms), copy to 'subject'
    if ("title" in record && record.title !== undefined) {
      const { title, ...rest } = record;
      return {
        ...rest,
        subject: title,
      };
    }
    return record;
  },
};

/**
 * Activities lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Now handles BOTH regular activities AND tasks after STI migration.
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { activitiesCallbacks } from './callbacks/activitiesCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   activitiesCallbacks,
 * ]);
 * ```
 */
export const activitiesCallbacks: ResourceCallbacks = createResourceCallbacks({
  resource: "activities",
  supportsSoftDelete: true,
  computedFields: COMPUTED_FIELDS,
  writeTransforms: [
    preserveSampleTypeTransform,
    handleTaskCompletionTimestamp,
    normalizeTaskSnoozeUntil,
    mapTaskTitleToSubject,
  ],
});
