/**
 * Activities Resource Lifecycle Callbacks
 *
 * Resource-specific logic for activities using React Admin's withLifecycleCallbacks pattern.
 * Uses the createResourceCallbacks factory for standard soft-delete behavior.
 *
 * Key behaviors:
 * 1. Soft delete - Sets deleted_at instead of hard delete
 * 2. Filter cleaning - Adds soft delete filter by default
 * 3. Data transformation - Strips computed fields from joins before save
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 */

import { createResourceCallbacks, type ResourceCallbacks } from "./createResourceCallbacks";

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by views or JOINs with contacts/organizations
 */
export const COMPUTED_FIELDS = [
  "contact_name",
  "organization_name",
  "opportunity_name",
] as const;

/**
 * Activities lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { activitiesCallbacks } from './callbacks/activitiesCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   activitiesCallbacks,
 * ]);
 * ```
 */
export const activitiesCallbacks: ResourceCallbacks = createResourceCallbacks({
  resource: "activities",
  supportsSoftDelete: true,
  computedFields: COMPUTED_FIELDS,
});
