/**
 * Contacts Resource Lifecycle Callbacks
 *
 * Resource-specific logic for contacts using React Admin's withLifecycleCallbacks pattern.
 * Uses the createResourceCallbacks factory for standard soft-delete behavior.
 *
 * Key behaviors:
 * 1. Soft delete - Sets deleted_at instead of hard delete
 * 2. JSONB normalization - Ensures email/phone/tags are always arrays
 * 3. Filter cleaning - Adds soft delete filter by default
 * 4. Data transformation - Strips computed fields before save
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 */

import type { RaRecord } from "ra-core";
import { createResourceCallbacks, type ResourceCallbacks } from "./createResourceCallbacks";
import { normalizeJsonbArrays } from "./commonTransforms";

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by views or computed in the frontend
 */
export const COMPUTED_FIELDS = [
  "full_name",
  "organization_name",
  "primary_organization_name",
  "total_opportunities",
  "last_activity_date",
] as const;

/**
 * JSONB array fields that need normalization
 * Database may return null/undefined but frontend expects arrays
 * @deprecated Import from commonTransforms instead
 */
export const JSONB_ARRAY_FIELDS = ["email", "phone", "tags"] as const;

/**
 * Re-export normalizeJsonbArrays from commonTransforms for backward compatibility
 * @deprecated Import from commonTransforms instead
 */
export { normalizeJsonbArrays } from "./commonTransforms";

/**
 * Contacts lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { contactsCallbacks } from './callbacks/contactsCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   contactsCallbacks,
 * ]);
 * ```
 */
export const contactsCallbacks: ResourceCallbacks = createResourceCallbacks({
  resource: "contacts",
  supportsSoftDelete: true,
  computedFields: COMPUTED_FIELDS,
  afterReadTransform: normalizeJsonbArrays,
});

/**
 * Export stripComputedFields for backward compatibility with tests
 * The factory handles this internally, but tests may import it directly
 */
export function stripComputedFields(data: Partial<RaRecord>): Partial<RaRecord> {
  const cleaned = { ...data };
  for (const field of COMPUTED_FIELDS) {
    delete cleaned[field];
  }
  return cleaned;
}
