/**
 * Contacts Resource Lifecycle Callbacks
 *
 * Resource-specific logic for contacts using React Admin's withLifecycleCallbacks pattern.
 * These callbacks are composed with the base DataProvider to add contacts-specific behavior.
 *
 * Key behaviors:
 * 1. Soft delete - Sets deleted_at instead of hard delete
 * 2. JSONB normalization - Ensures email/phone/tags are always arrays
 * 3. Filter cleaning - Adds soft delete filter by default
 * 4. Data transformation - Strips computed fields before save
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 */

import type { DataProvider, RaRecord, GetListParams, DeleteParams } from "ra-core";

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by views or computed in the frontend
 */
const COMPUTED_FIELDS = [
  "full_name",
  "organization_name",
  "primary_organization_name",
  "total_opportunities",
  "last_activity_date",
] as const;

/**
 * JSONB array fields that need normalization
 * Database may return null/undefined but frontend expects arrays
 */
const JSONB_ARRAY_FIELDS = ["email", "phone", "tags"] as const;

/**
 * Lifecycle callback type for React Admin withLifecycleCallbacks
 */
interface ResourceCallbacks {
  resource: string;
  beforeDelete?: (params: DeleteParams, dataProvider: DataProvider) => Promise<DeleteParams & { meta?: { skipDelete?: boolean } }>;
  afterRead?: (record: RaRecord, dataProvider: DataProvider) => Promise<RaRecord>;
  beforeGetList?: (params: GetListParams, dataProvider: DataProvider) => Promise<GetListParams>;
  beforeSave?: (data: Partial<RaRecord>, dataProvider: DataProvider, resource: string) => Promise<Partial<RaRecord>>;
}

/**
 * Normalize JSONB array fields to ensure they are always arrays
 * Prevents runtime errors when components expect array data
 *
 * @param record - The record from database
 * @returns Record with normalized array fields
 */
function normalizeJsonbArrays(record: RaRecord): RaRecord {
  const normalized = { ...record };

  for (const field of JSONB_ARRAY_FIELDS) {
    if (field in normalized) {
      const value = normalized[field];
      if (value === null || value === undefined) {
        normalized[field] = [];
      } else if (!Array.isArray(value)) {
        // Handle unexpected non-array values (shouldn't happen after migration)
        normalized[field] = typeof value === "object" ? [value] : [];
      }
    }
  }

  return normalized;
}

/**
 * Strip computed fields that shouldn't be sent to database
 *
 * @param data - The data being saved
 * @returns Data without computed fields
 */
function stripComputedFields(data: Partial<RaRecord>): Partial<RaRecord> {
  const cleaned = { ...data };

  for (const field of COMPUTED_FIELDS) {
    delete cleaned[field];
  }

  return cleaned;
}

/**
 * Contacts lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { contactsCallbacks } from './callbacks/contactsCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   contactsCallbacks,
 * ]);
 * ```
 */
export const contactsCallbacks: ResourceCallbacks = {
  resource: "contacts",

  /**
   * Convert hard delete to soft delete
   * Sets deleted_at timestamp instead of removing the record
   */
  beforeDelete: async (params, dataProvider) => {
    const deletedAt = new Date().toISOString();

    // Perform soft delete via update
    await dataProvider.update("contacts", {
      id: params.id,
      data: { deleted_at: deletedAt },
      previousData: params.previousData,
    });

    // Return params with meta flag to skip actual delete
    return {
      ...params,
      meta: { ...params.meta, skipDelete: true },
    };
  },

  /**
   * Normalize JSONB array fields after reading from database
   * Ensures email, phone, tags are always arrays
   */
  afterRead: async (record, _dataProvider) => {
    return normalizeJsonbArrays(record);
  },

  /**
   * Add soft delete filter and clean filters before getList
   * Excludes soft-deleted records by default
   */
  beforeGetList: async (params, _dataProvider) => {
    const { includeDeleted, ...otherFilters } = params.filter || {};

    // Add soft delete filter unless explicitly including deleted
    const softDeleteFilter = includeDeleted ? {} : { "deleted_at@is": null };

    return {
      ...params,
      filter: {
        ...otherFilters,
        ...softDeleteFilter,
      },
    };
  },

  /**
   * Strip computed fields before save (create/update)
   * Removes fields that are generated by views or computed
   */
  beforeSave: async (data, _dataProvider, _resource) => {
    return stripComputedFields(data);
  },
};

/**
 * Export helper functions for testing
 */
export { normalizeJsonbArrays, stripComputedFields, COMPUTED_FIELDS, JSONB_ARRAY_FIELDS };
