/**
 * Opportunities Resource Lifecycle Callbacks
 *
 * Resource-specific logic for opportunities using React Admin's withLifecycleCallbacks pattern.
 * More complex than contacts/organizations due to:
 * 1. Cascading soft delete via RPC (archive_opportunity_with_relations)
 * 2. Product sync handled at provider level (products_to_sync → RPC)
 * 3. Default value merging for create validation
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 */

import type { DataProvider, RaRecord, GetListParams, DeleteParams } from "ra-core";

/**
 * Extended DataProvider type with RPC method
 */
interface DataProviderWithRpc extends DataProvider {
  rpc?: (functionName: string, params: Record<string, unknown>) => Promise<unknown>;
}

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by views or aggregations
 */
const COMPUTED_FIELDS = [
  "principal_organization_name",
  "total_value",
  "participant_count",
  "contact_count",
  "product_count",
  "last_activity_date",
  "days_in_stage",
] as const;

/**
 * Default values for opportunity create
 * Used to ensure validation passes when fields are missing
 */
const CREATE_DEFAULTS = {
  contact_ids: [] as number[],
} as const;

/**
 * Lifecycle callback type for React Admin withLifecycleCallbacks
 */
interface ResourceCallbacks {
  resource: string;
  beforeDelete?: (params: DeleteParams, dataProvider: DataProvider) => Promise<DeleteParams & { meta?: { skipDelete?: boolean } }>;
  afterRead?: (record: RaRecord, dataProvider: DataProvider) => Promise<RaRecord>;
  beforeGetList?: (params: GetListParams, dataProvider: DataProvider) => Promise<GetListParams>;
  beforeSave?: (data: Partial<RaRecord>, dataProvider: DataProvider, resource: string) => Promise<Partial<RaRecord>>;
}

/**
 * Strip computed fields that shouldn't be sent to database
 *
 * @param data - The data being saved
 * @returns Data without computed fields
 */
function stripComputedFields(data: Partial<RaRecord>): Partial<RaRecord> {
  const cleaned = { ...data };

  for (const field of COMPUTED_FIELDS) {
    delete cleaned[field];
  }

  return cleaned;
}

/**
 * Merge default values for create operation
 * Ensures required fields have values for validation
 *
 * @param data - The data being created
 * @returns Data with defaults merged
 */
function mergeCreateDefaults(data: Partial<RaRecord>): Partial<RaRecord> {
  return {
    ...CREATE_DEFAULTS,
    ...data,
  };
}

/**
 * Opportunities lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { opportunitiesCallbacks } from './callbacks/opportunitiesCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   opportunitiesCallbacks,
 * ]);
 * ```
 */
export const opportunitiesCallbacks: ResourceCallbacks = {
  resource: "opportunities",

  /**
   * Use archive RPC for cascading soft delete
   * This archives the opportunity AND all related records:
   * - activities
   * - opportunityNotes
   * - opportunity_participants
   * - tasks
   */
  beforeDelete: async (params, dataProvider) => {
    const dpWithRpc = dataProvider as DataProviderWithRpc;

    if (!dpWithRpc.rpc) {
      throw new Error("Archive opportunity failed: DataProvider does not support RPC");
    }

    try {
      await dpWithRpc.rpc("archive_opportunity_with_relations", {
        opp_id: params.id,
      });
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      console.error(`[opportunitiesCallbacks] Archive failed`, {
        opportunityId: params.id,
        error,
      });
      throw new Error(`Archive opportunity failed: ${message}`);
    }

    // Return params with meta flag to skip actual delete
    return {
      ...params,
      meta: { ...params.meta, skipDelete: true },
    };
  },

  /**
   * Normalize data after reading from database
   * Opportunities don't have JSONB arrays, but we keep this for consistency
   */
  afterRead: async (record, _dataProvider) => {
    // No transformation needed - dates and values are already properly formatted
    return record;
  },

  /**
   * Add soft delete filter and clean filters before getList
   * Excludes soft-deleted records by default
   */
  beforeGetList: async (params, _dataProvider) => {
    const { includeDeleted, ...otherFilters } = params.filter || {};

    // Add soft delete filter unless explicitly including deleted
    const softDeleteFilter = includeDeleted ? {} : { "deleted_at@is": null };

    return {
      ...params,
      filter: {
        ...otherFilters,
        ...softDeleteFilter,
      },
    };
  },

  /**
   * Process data before save (create/update)
   * - Strip computed fields
   * - Merge defaults for create
   * - Preserve products_to_sync for RPC handling at provider level
   */
  beforeSave: async (data, _dataProvider, _resource) => {
    // Strip computed fields first
    let processed = stripComputedFields(data);

    // Merge defaults for create (when no id present)
    if (!data.id) {
      processed = mergeCreateDefaults(processed);
    }

    return processed;
  },
};

/**
 * Export helper functions for testing
 */
export { stripComputedFields, mergeCreateDefaults, COMPUTED_FIELDS, CREATE_DEFAULTS };
