/**
 * Organizations Resource Lifecycle Callbacks
 *
 * Resource-specific logic for organizations using React Admin's withLifecycleCallbacks pattern.
 * Uses the createResourceCallbacks factory for standard soft-delete behavior.
 *
 * Key behaviors:
 * 1. Soft delete - Sets deleted_at instead of hard delete
 * 2. Filter cleaning - Adds soft delete filter by default
 * 3. Data transformation - Strips computed fields before save
 * 4. Logo handling - Preserved by storage service
 * 5. Search transformation - Transforms q filter into ILIKE search on name, city, state, sector
 *
 * Engineering Constitution: Resource-specific logic extracted for single responsibility
 */

import type { RaRecord, GetListParams, DataProvider } from "ra-core";
import { createResourceCallbacks, type ResourceCallbacks } from "./createResourceCallbacks";
import { createQToIlikeTransformer } from "./commonTransforms";

/**
 * Computed fields that should be stripped before saving to database
 * These are generated by the organizations_summary view or aggregations
 */
export const COMPUTED_FIELDS = [
  "contact_count",
  "opportunity_count",
  "total_revenue",
  "last_activity_date",
  "primary_contact_name",
  // From organizations_summary view (nb_* naming convention)
  "nb_contacts",
  "nb_opportunities",
  "nb_notes",
  // Hierarchy/parent fields
  "parent_organization_name",
  "child_branch_count",
  "total_contacts_across_branches",
  "total_opportunities_across_branches",
  "last_opportunity_activity",
  // PostgreSQL tsvector - auto-generated, cannot be updated
  "search_tsv",
] as const;

/**
 * Fields to search when q filter is provided
 * These fields will be searched with ILIKE for partial matching
 */
export const ORGANIZATIONS_SEARCH_FIELDS = ["name", "city", "state", "sector"] as const;

/**
 * Transform q filter into ILIKE search on organization fields
 * Uses raw PostgREST mode to handle multi-word searches correctly
 *
 * WORKAROUND for ra-data-postgrest library bug:
 * The library splits multi-word ILIKE values on whitespace and has a bug
 * handling 3+ words. Uses "or@" key with escaping to bypass this issue.
 *
 * @see createQToIlikeTransformer in commonTransforms.ts (useRawPostgrest mode)
 */
export const transformQToIlikeSearch = createQToIlikeTransformer({
  searchFields: ORGANIZATIONS_SEARCH_FIELDS,
  useRawPostgrest: true,
});

/**
 * Base callbacks from factory (soft delete, computed fields, transforms)
 * We extract this so we can override beforeGetList with search support
 */
const baseCallbacks = createResourceCallbacks({
  resource: "organizations",
  supportsSoftDelete: true,
  computedFields: COMPUTED_FIELDS,
});

/**
 * Custom beforeGetList that chains:
 * 1. q filter → ILIKE search transformation
 * 2. Soft delete filter (from base callbacks)
 *
 * This matches the unified data provider's search behavior while preserving
 * the factory's soft-delete filtering.
 */
async function organizationsBeforeGetList(
  params: GetListParams,
  dataProvider: DataProvider
): Promise<GetListParams> {
  // Step 1: Transform q filter to ILIKE search (removes q from filter)
  const searchTransformedParams = transformQToIlikeSearch(params);

  // Step 2: Apply soft delete filter from base callbacks
  // The base callback will add deleted_at@is: null unless includeDeleted is true
  if (baseCallbacks.beforeGetList) {
    return baseCallbacks.beforeGetList(searchTransformedParams, dataProvider);
  }

  return searchTransformedParams;
}

/**
 * Organizations lifecycle callbacks for React Admin withLifecycleCallbacks
 *
 * Usage:
 * ```typescript
 * import { withLifecycleCallbacks } from 'react-admin';
 * import { organizationsCallbacks } from './callbacks/organizationsCallbacks';
 *
 * const dataProvider = withLifecycleCallbacks(baseProvider, [
 *   organizationsCallbacks,
 * ]);
 * ```
 */
export const organizationsCallbacks: ResourceCallbacks = {
  ...baseCallbacks,
  beforeGetList: organizationsBeforeGetList,
};

/**
 * Export stripComputedFields for backward compatibility with tests
 * The factory handles this internally, but tests may import it directly
 */
export function stripComputedFields(data: Partial<RaRecord>): Partial<RaRecord> {
  const cleaned = { ...data };
  for (const field of COMPUTED_FIELDS) {
    delete cleaned[field];
  }
  return cleaned;
}
