-- supabase/migrations/20251206000001_create_tutorial_progress.sql

-- Tutorial progress tracking for first-time user wizard
CREATE TABLE public.tutorial_progress (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sales_id bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,

  -- Step completion tracking (order: org → contact → opp → activity → task)
  organization_completed boolean NOT NULL DEFAULT false,
  contact_completed boolean NOT NULL DEFAULT false,
  opportunity_completed boolean NOT NULL DEFAULT false,
  activity_completed boolean NOT NULL DEFAULT false,
  task_completed boolean NOT NULL DEFAULT false,

  -- IDs of created records (for linking between steps)
  created_organization_id bigint REFERENCES public.organizations(id) ON DELETE SET NULL,
  created_contact_id bigint REFERENCES public.contacts(id) ON DELETE SET NULL,
  created_opportunity_id bigint REFERENCES public.opportunities(id) ON DELETE SET NULL,
  created_activity_id bigint REFERENCES public.activities(id) ON DELETE SET NULL,
  created_task_id bigint REFERENCES public.tasks(id) ON DELETE SET NULL,

  -- Dismissal tracking
  dismissed boolean NOT NULL DEFAULT false,
  dismissed_at timestamp with time zone,

  -- Timestamps
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),

  -- One progress record per user
  CONSTRAINT unique_sales_tutorial UNIQUE (sales_id)
);

-- Enable RLS
ALTER TABLE public.tutorial_progress ENABLE ROW LEVEL SECURITY;

-- RLS policies: users can only access their own tutorial progress
CREATE POLICY "Users can view own tutorial progress"
  ON public.tutorial_progress FOR SELECT
  USING (sales_id = public.get_current_sales_id());

CREATE POLICY "Users can insert own tutorial progress"
  ON public.tutorial_progress FOR INSERT
  WITH CHECK (sales_id = public.get_current_sales_id());

CREATE POLICY "Users can update own tutorial progress"
  ON public.tutorial_progress FOR UPDATE
  USING (sales_id = public.get_current_sales_id())
  WITH CHECK (sales_id = public.get_current_sales_id());

-- Grant permissions
GRANT SELECT, INSERT, UPDATE ON public.tutorial_progress TO authenticated;
GRANT USAGE ON SEQUENCE public.tutorial_progress_id_seq TO authenticated;

-- Add comment for documentation
COMMENT ON TABLE public.tutorial_progress IS 'Tracks first-time tutorial wizard progress per user';
